
# This file is automatically generated, you probably don't want to edit this

BrawSimOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSimOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            topMode = NULL,
            simPlanHelp = NULL,
            simSingleHelp = NULL,
            simMultipleHelp = NULL,
            simExploreHelp = NULL,
            planMode = NULL,
            presetDV = "DV",
            presetIV = "IV",
            presetIV2 = "none",
            DVname = "DV",
            DVtype = "Interval",
            DVmu = 0,
            DVsd = 1,
            DVskew = 0,
            DVkurt = 0,
            DVnlevs = 7,
            DViqr = 4,
            DVncats = 2,
            DVcases = "C1,C2",
            DVprops = "1,1",
            IVname = "IV",
            IVtype = "Interval",
            IVmu = 0,
            IVsd = 1,
            IVskew = 0,
            IVkurt = 0,
            IVnlevs = 7,
            IViqr = 4,
            IVncats = 2,
            IVcases = "C1,C2",
            IVprops = "1,1",
            IV2name = "IV2",
            IV2type = "Interval",
            IV2mu = 0,
            IV2sd = 1,
            IV2skew = 0,
            IV2kurt = 0,
            IV2nlevs = 7,
            IV2iqr = 4,
            IV2ncats = 2,
            IV2cases = "C1,C2",
            IV2props = "1,1",
            EffectSize1 = 0,
            EffectSize2 = 0,
            EffectSize3 = 0,
            EffectSize12 = 0,
            EffectConfig = "normal",
            rSD = 0,
            Heteroscedasticity = 0,
            Residuals = "normal",
            WorldOn = FALSE,
            WorldPDF = "Exp",
            WorldRZ = "z",
            worldMeanRplus = 0.3,
            WorldShape = 1,
            worldPRnull = 0.5,
            WorldSampleRs = 0,
            WorldSampleN = 42,
            WorldSample = "none",
            SampleSize = 42,
            SampleSizeDist = "Gamma",
            SampleSizeM = 52,
            SampleSpreadOn = FALSE,
            SampleSD = 33.3,
            SampleMethod = "Random",
            PoorSamplingAmount = 0.1,
            SampleUsage1 = "Between",
            SampleUsage2 = "Between",
            Dependence = 0,
            Outliers = 0,
            NonResponse = 0,
            LimitRangeIV = "no",
            RangeMinIV = -3,
            RangeMaxIV = 3,
            LimitRangeIV2 = "no",
            RangeMinIV2 = -3,
            RangeMaxIV2 = 3,
            Cheating = "None",
            CheatingBudget = 0.1,
            ReplicationOn = FALSE,
            ReplicationPower = 0.8,
            ReplicationPrior = "None",
            ReplicationAttempts = 1,
            ReplicationDecision = "Cautious",
            RepMaxN = 100000,
            ReplicationAlpha = 0.05,
            STMethod = NULL,
            alphaSig = 0.05,
            minRp = 0,
            keepOnlySig = "no",
            biasAmount = 1,
            ssq = "Type3",
            main1 = TRUE,
            main2 = TRUE,
            interaction = FALSE,
            covariation = FALSE,
            equalVar = "yes",
            Transform = "None",
            likelihoodType = "Populations",
            likelihoodCutaway = "cutaway",
            likelihoodUsePrior = "none",
            priorPDF = "Exp",
            priorRZ = "z",
            priorMeanRplus = 0.3,
            priorPRplus = 1,
            useAIC = "none",
            MetaAnalysisOn = FALSE,
            MetaAnalysisType = "random",
            MetaAnalysisDist = "Simple",
            MetaAnalysisPrior = "none",
            MetaAnalysisNulls = FALSE,
            MetaAnalysisBias = FALSE,
            MetaAnalysisNStudies = 20,
            MetaAnalysisMethod = "MLE",
            MetaAnalysisStudiesSig = "no",
            metaVar1 = "metaRiv",
            metaVar2 = "metaRsd",
            makeSampleBtn = FALSE,
            numberSamples = 100,
            makeMultipleBtn = NULL,
            stopBtn = NULL,
            inferVar1 = "rs",
            inferVar2 = "p",
            showSampleType = "Basic",
            showInferDimension = "1D",
            reportInferStats = "Medians",
            showMultipleParam = "Basic",
            showMultipleDimension = "1D",
            exploreNPointsH = 11,
            exploreNPointsD = 11,
            exploreNPointsA = 11,
            exploreNPointsM = 11,
            exploreMinValH = "-0.9",
            exploreMaxValH = "0.9",
            exploreMinValD = "10",
            exploreMaxValD = "250",
            exploreMinValA = "0.001",
            exploreMaxValM = "0.5",
            exploreMinValM = "0.001",
            exploreMaxValA = "0.5",
            exploreXLogH = FALSE,
            exploreXLogD = FALSE,
            exploreXLogA = FALSE,
            exploreXLogM = FALSE,
            numberExplores = 10,
            makeExploreBtn = NULL,
            exploreMode = "designExplore",
            hypothesisExploreList = NULL,
            designExploreList = NULL,
            analysisExploreList = NULL,
            moreExploreList = NULL,
            showExploreParam = "Basic",
            showExploreStyle = "stats",
            whichShowMultiple = "all",
            brawHelp = FALSE,
            showHistory = TRUE,
            showGraphs = "HTML",
            fixedAxes = FALSE,
            shorthandCalculations = FALSE,
            dispRZ = "r",
            simGoBack = NULL,
            simGoForwards = NULL, ...) {

            super$initialize(
                package="BrawStats",
                name="BrawSim",
                requiresData=FALSE,
                ...)

            private$..topMode <- jmvcore::OptionList$new(
                "topMode",
                topMode,
                options=list(
                    "Simulation",
                    "Settings"))
            private$..simPlanHelp <- jmvcore::OptionAction$new(
                "simPlanHelp",
                simPlanHelp)
            private$..simSingleHelp <- jmvcore::OptionAction$new(
                "simSingleHelp",
                simSingleHelp)
            private$..simMultipleHelp <- jmvcore::OptionAction$new(
                "simMultipleHelp",
                simMultipleHelp)
            private$..simExploreHelp <- jmvcore::OptionAction$new(
                "simExploreHelp",
                simExploreHelp)
            private$..planMode <- jmvcore::OptionList$new(
                "planMode",
                planMode,
                options=list(
                    "planH",
                    "planD",
                    "planA",
                    "planW",
                    "planM"))
            private$..presetDV <- jmvcore::OptionList$new(
                "presetDV",
                presetDV,
                options=list(
                    "DV",
                    "IQ",
                    "Diligence",
                    "Perfectionism",
                    "Anxiety",
                    "Happiness",
                    "SelfConfidence",
                    "HoursSleep",
                    "ExamGrade",
                    "ExamPass",
                    "RiskTaking",
                    "Interesting",
                    "Musician",
                    "Smoker",
                    "RiskTaker",
                    "Outcome",
                    "Phase",
                    "StudySubject",
                    "BirthOrder"),
                default="DV")
            private$..presetIV <- jmvcore::OptionList$new(
                "presetIV",
                presetIV,
                options=list(
                    "IV",
                    "IQ",
                    "Diligence",
                    "Perfectionism",
                    "Anxiety",
                    "Happiness",
                    "SelfConfidence",
                    "HoursSleep",
                    "ExamGrade",
                    "RiskTaking",
                    "Interesting",
                    "Musician",
                    "Smoker",
                    "RiskTaker",
                    "Treatment",
                    "Phase",
                    "StudySubject",
                    "BirthOrder"),
                default="IV")
            private$..presetIV2 <- jmvcore::OptionList$new(
                "presetIV2",
                presetIV2,
                options=list(
                    "none",
                    "IV2",
                    "IQ",
                    "Diligence",
                    "Perfectionism",
                    "Anxiety",
                    "Happiness",
                    "SelfConfidence",
                    "HoursSleep",
                    "ExamGrade",
                    "RiskTaking",
                    "Interesting",
                    "Musician",
                    "Smoker",
                    "RiskTaker",
                    "Treatment",
                    "Phase",
                    "StudySubject",
                    "BirthOrder"),
                default="none")
            private$..DVname <- jmvcore::OptionString$new(
                "DVname",
                DVname,
                default="DV")
            private$..DVtype <- jmvcore::OptionList$new(
                "DVtype",
                DVtype,
                options=list(
                    "Interval",
                    "Ordinal",
                    "Categorical"),
                default="Interval")
            private$..DVmu <- jmvcore::OptionNumber$new(
                "DVmu",
                DVmu,
                default=0)
            private$..DVsd <- jmvcore::OptionNumber$new(
                "DVsd",
                DVsd,
                default=1)
            private$..DVskew <- jmvcore::OptionNumber$new(
                "DVskew",
                DVskew,
                default=0)
            private$..DVkurt <- jmvcore::OptionNumber$new(
                "DVkurt",
                DVkurt,
                default=0)
            private$..DVnlevs <- jmvcore::OptionNumber$new(
                "DVnlevs",
                DVnlevs,
                default=7)
            private$..DViqr <- jmvcore::OptionNumber$new(
                "DViqr",
                DViqr,
                default=4)
            private$..DVncats <- jmvcore::OptionNumber$new(
                "DVncats",
                DVncats,
                default=2)
            private$..DVcases <- jmvcore::OptionString$new(
                "DVcases",
                DVcases,
                default="C1,C2")
            private$..DVprops <- jmvcore::OptionString$new(
                "DVprops",
                DVprops,
                default="1,1")
            private$..IVname <- jmvcore::OptionString$new(
                "IVname",
                IVname,
                default="IV")
            private$..IVtype <- jmvcore::OptionList$new(
                "IVtype",
                IVtype,
                options=list(
                    "Interval",
                    "Ordinal",
                    "Categorical"),
                default="Interval")
            private$..IVmu <- jmvcore::OptionNumber$new(
                "IVmu",
                IVmu,
                default=0)
            private$..IVsd <- jmvcore::OptionNumber$new(
                "IVsd",
                IVsd,
                default=1)
            private$..IVskew <- jmvcore::OptionNumber$new(
                "IVskew",
                IVskew,
                default=0)
            private$..IVkurt <- jmvcore::OptionNumber$new(
                "IVkurt",
                IVkurt,
                default=0)
            private$..IVnlevs <- jmvcore::OptionNumber$new(
                "IVnlevs",
                IVnlevs,
                default=7)
            private$..IViqr <- jmvcore::OptionNumber$new(
                "IViqr",
                IViqr,
                default=4)
            private$..IVncats <- jmvcore::OptionNumber$new(
                "IVncats",
                IVncats,
                default=2)
            private$..IVcases <- jmvcore::OptionString$new(
                "IVcases",
                IVcases,
                default="C1,C2")
            private$..IVprops <- jmvcore::OptionString$new(
                "IVprops",
                IVprops,
                default="1,1")
            private$..IV2name <- jmvcore::OptionString$new(
                "IV2name",
                IV2name,
                default="IV2")
            private$..IV2type <- jmvcore::OptionList$new(
                "IV2type",
                IV2type,
                options=list(
                    "Interval",
                    "Ordinal",
                    "Categorical"),
                default="Interval")
            private$..IV2mu <- jmvcore::OptionNumber$new(
                "IV2mu",
                IV2mu,
                default=0)
            private$..IV2sd <- jmvcore::OptionNumber$new(
                "IV2sd",
                IV2sd,
                default=1)
            private$..IV2skew <- jmvcore::OptionNumber$new(
                "IV2skew",
                IV2skew,
                default=0)
            private$..IV2kurt <- jmvcore::OptionNumber$new(
                "IV2kurt",
                IV2kurt,
                default=0)
            private$..IV2nlevs <- jmvcore::OptionNumber$new(
                "IV2nlevs",
                IV2nlevs,
                default=7)
            private$..IV2iqr <- jmvcore::OptionNumber$new(
                "IV2iqr",
                IV2iqr,
                default=4)
            private$..IV2ncats <- jmvcore::OptionNumber$new(
                "IV2ncats",
                IV2ncats,
                default=2)
            private$..IV2cases <- jmvcore::OptionString$new(
                "IV2cases",
                IV2cases,
                default="C1,C2")
            private$..IV2props <- jmvcore::OptionString$new(
                "IV2props",
                IV2props,
                default="1,1")
            private$..EffectSize1 <- jmvcore::OptionNumber$new(
                "EffectSize1",
                EffectSize1,
                default=0)
            private$..EffectSize2 <- jmvcore::OptionNumber$new(
                "EffectSize2",
                EffectSize2,
                default=0)
            private$..EffectSize3 <- jmvcore::OptionNumber$new(
                "EffectSize3",
                EffectSize3,
                default=0)
            private$..EffectSize12 <- jmvcore::OptionNumber$new(
                "EffectSize12",
                EffectSize12,
                default=0)
            private$..EffectConfig <- jmvcore::OptionList$new(
                "EffectConfig",
                EffectConfig,
                options=list(
                    "simple",
                    "normal",
                    "moderation",
                    "mediation",
                    "path",
                    "lpath"),
                default="normal")
            private$..rSD <- jmvcore::OptionNumber$new(
                "rSD",
                rSD,
                default=0)
            private$..Heteroscedasticity <- jmvcore::OptionNumber$new(
                "Heteroscedasticity",
                Heteroscedasticity,
                default=0)
            private$..Residuals <- jmvcore::OptionList$new(
                "Residuals",
                Residuals,
                options=list(
                    "normal",
                    "skewed",
                    "uniform",
                    "cauchy"),
                default="normal")
            private$..WorldOn <- jmvcore::OptionBool$new(
                "WorldOn",
                WorldOn,
                default=FALSE)
            private$..WorldPDF <- jmvcore::OptionList$new(
                "WorldPDF",
                WorldPDF,
                options=list(
                    "Single",
                    "Double",
                    "Uniform",
                    "Gauss",
                    "Exp",
                    "GenExp",
                    "Gamma"),
                default="Exp")
            private$..WorldRZ <- jmvcore::OptionList$new(
                "WorldRZ",
                WorldRZ,
                options=list(
                    "r",
                    "z"),
                default="z")
            private$..worldMeanRplus <- jmvcore::OptionNumber$new(
                "worldMeanRplus",
                worldMeanRplus,
                default=0.3)
            private$..WorldShape <- jmvcore::OptionNumber$new(
                "WorldShape",
                WorldShape,
                default=1)
            private$..worldPRnull <- jmvcore::OptionNumber$new(
                "worldPRnull",
                worldPRnull,
                default=0.5)
            private$..WorldSampleRs <- jmvcore::OptionNumber$new(
                "WorldSampleRs",
                WorldSampleRs,
                default=0)
            private$..WorldSampleN <- jmvcore::OptionNumber$new(
                "WorldSampleN",
                WorldSampleN,
                default=42)
            private$..WorldSample <- jmvcore::OptionList$new(
                "WorldSample",
                WorldSample,
                options=list(
                    "none",
                    "plain",
                    "bias"),
                default="none")
            private$..SampleSize <- jmvcore::OptionNumber$new(
                "SampleSize",
                SampleSize,
                default=42)
            private$..SampleSizeDist <- jmvcore::OptionList$new(
                "SampleSizeDist",
                SampleSizeDist,
                options=list(
                    "Gamma",
                    "Gauss",
                    "Exp",
                    "Uniform"),
                default="Gamma")
            private$..SampleSizeM <- jmvcore::OptionNumber$new(
                "SampleSizeM",
                SampleSizeM,
                default=52)
            private$..SampleSpreadOn <- jmvcore::OptionBool$new(
                "SampleSpreadOn",
                SampleSpreadOn,
                default=FALSE)
            private$..SampleSD <- jmvcore::OptionNumber$new(
                "SampleSD",
                SampleSD,
                default=33.3)
            private$..SampleMethod <- jmvcore::OptionList$new(
                "SampleMethod",
                SampleMethod,
                options=list(
                    "Random",
                    "Stratified",
                    "Limited",
                    "Cluster",
                    "Snowball",
                    "Convenience"),
                default="Random")
            private$..PoorSamplingAmount <- jmvcore::OptionNumber$new(
                "PoorSamplingAmount",
                PoorSamplingAmount,
                default=0.1)
            private$..SampleUsage1 <- jmvcore::OptionList$new(
                "SampleUsage1",
                SampleUsage1,
                options=list(
                    "Between",
                    "Within"),
                default="Between")
            private$..SampleUsage2 <- jmvcore::OptionList$new(
                "SampleUsage2",
                SampleUsage2,
                options=list(
                    "Between",
                    "Within"),
                default="Between")
            private$..Dependence <- jmvcore::OptionNumber$new(
                "Dependence",
                Dependence,
                default=0)
            private$..Outliers <- jmvcore::OptionNumber$new(
                "Outliers",
                Outliers,
                default=0)
            private$..NonResponse <- jmvcore::OptionNumber$new(
                "NonResponse",
                NonResponse,
                default=0)
            private$..LimitRangeIV <- jmvcore::OptionList$new(
                "LimitRangeIV",
                LimitRangeIV,
                options=list(
                    "yes",
                    "no"),
                default="no")
            private$..RangeMinIV <- jmvcore::OptionNumber$new(
                "RangeMinIV",
                RangeMinIV,
                default=-3)
            private$..RangeMaxIV <- jmvcore::OptionNumber$new(
                "RangeMaxIV",
                RangeMaxIV,
                default=3)
            private$..LimitRangeIV2 <- jmvcore::OptionList$new(
                "LimitRangeIV2",
                LimitRangeIV2,
                options=list(
                    "yes",
                    "no"),
                default="no")
            private$..RangeMinIV2 <- jmvcore::OptionNumber$new(
                "RangeMinIV2",
                RangeMinIV2,
                default=-3)
            private$..RangeMaxIV2 <- jmvcore::OptionNumber$new(
                "RangeMaxIV2",
                RangeMaxIV2,
                default=3)
            private$..Cheating <- jmvcore::OptionList$new(
                "Cheating",
                Cheating,
                options=list(
                    "None",
                    "Grow",
                    "Prune",
                    "Replace",
                    "Retry"),
                default="None")
            private$..CheatingBudget <- jmvcore::OptionNumber$new(
                "CheatingBudget",
                CheatingBudget,
                default=0.1)
            private$..ReplicationOn <- jmvcore::OptionBool$new(
                "ReplicationOn",
                ReplicationOn,
                default=FALSE)
            private$..ReplicationPower <- jmvcore::OptionNumber$new(
                "ReplicationPower",
                ReplicationPower,
                default=0.8)
            private$..ReplicationPrior <- jmvcore::OptionList$new(
                "ReplicationPrior",
                ReplicationPrior,
                options=list(
                    "None",
                    "World",
                    "Prior"),
                default="None")
            private$..ReplicationAttempts <- jmvcore::OptionNumber$new(
                "ReplicationAttempts",
                ReplicationAttempts,
                default=1)
            private$..ReplicationDecision <- jmvcore::OptionList$new(
                "ReplicationDecision",
                ReplicationDecision,
                options=list(
                    "Cautious",
                    "Last",
                    "LargeN",
                    "MetaAnalysis"),
                default="Cautious")
            private$..RepMaxN <- jmvcore::OptionNumber$new(
                "RepMaxN",
                RepMaxN,
                default=100000)
            private$..ReplicationAlpha <- jmvcore::OptionNumber$new(
                "ReplicationAlpha",
                ReplicationAlpha,
                default=0.05)
            private$..STMethod <- jmvcore::OptionList$new(
                "STMethod",
                STMethod,
                options=list(
                    "NHST",
                    "dLLR"))
            private$..alphaSig <- jmvcore::OptionNumber$new(
                "alphaSig",
                alphaSig,
                default=0.05)
            private$..minRp <- jmvcore::OptionNumber$new(
                "minRp",
                minRp,
                default=0)
            private$..keepOnlySig <- jmvcore::OptionList$new(
                "keepOnlySig",
                keepOnlySig,
                options=list(
                    "yes",
                    "no"),
                default="no")
            private$..biasAmount <- jmvcore::OptionNumber$new(
                "biasAmount",
                biasAmount,
                default=1)
            private$..ssq <- jmvcore::OptionList$new(
                "ssq",
                ssq,
                options=list(
                    "Type1",
                    "Type2",
                    "Type3"),
                default="Type3")
            private$..main1 <- jmvcore::OptionBool$new(
                "main1",
                main1,
                default=TRUE)
            private$..main2 <- jmvcore::OptionBool$new(
                "main2",
                main2,
                default=TRUE)
            private$..interaction <- jmvcore::OptionBool$new(
                "interaction",
                interaction,
                default=FALSE)
            private$..covariation <- jmvcore::OptionBool$new(
                "covariation",
                covariation,
                default=FALSE)
            private$..equalVar <- jmvcore::OptionList$new(
                "equalVar",
                equalVar,
                options=list(
                    "no",
                    "yes"),
                default="yes")
            private$..Transform <- jmvcore::OptionList$new(
                "Transform",
                Transform,
                options=list(
                    "None",
                    "Log",
                    "Exp"),
                default="None")
            private$..likelihoodType <- jmvcore::OptionList$new(
                "likelihoodType",
                likelihoodType,
                options=list(
                    "Samples",
                    "Populations"),
                default="Populations")
            private$..likelihoodCutaway <- jmvcore::OptionList$new(
                "likelihoodCutaway",
                likelihoodCutaway,
                options=list(
                    "all",
                    "cutaway"),
                default="cutaway")
            private$..likelihoodUsePrior <- jmvcore::OptionList$new(
                "likelihoodUsePrior",
                likelihoodUsePrior,
                options=list(
                    "none",
                    "world",
                    "prior"),
                default="none")
            private$..priorPDF <- jmvcore::OptionList$new(
                "priorPDF",
                priorPDF,
                options=list(
                    "Single",
                    "Double",
                    "Uniform",
                    "Gauss",
                    "Exp"),
                default="Exp")
            private$..priorRZ <- jmvcore::OptionList$new(
                "priorRZ",
                priorRZ,
                options=list(
                    "r",
                    "z"),
                default="z")
            private$..priorMeanRplus <- jmvcore::OptionNumber$new(
                "priorMeanRplus",
                priorMeanRplus,
                default=0.3)
            private$..priorPRplus <- jmvcore::OptionNumber$new(
                "priorPRplus",
                priorPRplus,
                default=1)
            private$..useAIC <- jmvcore::OptionList$new(
                "useAIC",
                useAIC,
                options=list(
                    "none",
                    "AIC",
                    "BIC",
                    "CAIC",
                    "AICc"),
                default="none")
            private$..MetaAnalysisOn <- jmvcore::OptionBool$new(
                "MetaAnalysisOn",
                MetaAnalysisOn,
                default=FALSE)
            private$..MetaAnalysisType <- jmvcore::OptionList$new(
                "MetaAnalysisType",
                MetaAnalysisType,
                options=list(
                    "fixed",
                    "random",
                    "world"),
                default="random")
            private$..MetaAnalysisDist <- jmvcore::OptionList$new(
                "MetaAnalysisDist",
                MetaAnalysisDist,
                options=list(
                    "Single",
                    "Gauss",
                    "Exp",
                    "GenExp",
                    "Gamma",
                    "Simple",
                    "All"),
                default="Simple")
            private$..MetaAnalysisPrior <- jmvcore::OptionList$new(
                "MetaAnalysisPrior",
                MetaAnalysisPrior,
                options=list(
                    "none",
                    "uniform",
                    "world"),
                default="none")
            private$..MetaAnalysisNulls <- jmvcore::OptionBool$new(
                "MetaAnalysisNulls",
                MetaAnalysisNulls,
                default=FALSE)
            private$..MetaAnalysisBias <- jmvcore::OptionBool$new(
                "MetaAnalysisBias",
                MetaAnalysisBias,
                default=FALSE)
            private$..MetaAnalysisNStudies <- jmvcore::OptionNumber$new(
                "MetaAnalysisNStudies",
                MetaAnalysisNStudies,
                default=20)
            private$..MetaAnalysisMethod <- jmvcore::OptionList$new(
                "MetaAnalysisMethod",
                MetaAnalysisMethod,
                options=list(
                    "MLE",
                    "TF",
                    "Rep"),
                default="MLE")
            private$..MetaAnalysisStudiesSig <- jmvcore::OptionList$new(
                "MetaAnalysisStudiesSig",
                MetaAnalysisStudiesSig,
                options=list(
                    "no",
                    "yes"),
                default="no")
            private$..metaVar1 <- jmvcore::OptionList$new(
                "metaVar1",
                metaVar1,
                options=list(
                    "metaRiv",
                    "metaRsd",
                    "blank1",
                    "metaK",
                    "metaShape",
                    "metaSpread",
                    "blank2",
                    "metaPRplus",
                    "metaBias",
                    "metaSmax"),
                default="metaRiv")
            private$..metaVar2 <- jmvcore::OptionList$new(
                "metaVar2",
                metaVar2,
                options=list(
                    "metaRiv",
                    "metaRsd",
                    "blank1",
                    "metaK",
                    "metaShape",
                    "metaSpread",
                    "blank2",
                    "metaPRplus",
                    "metaBias",
                    "metaSmax"),
                default="metaRsd")
            private$..makeSampleBtn <- jmvcore::OptionAction$new(
                "makeSampleBtn",
                makeSampleBtn,
                default=FALSE)
            private$..numberSamples <- jmvcore::OptionNumber$new(
                "numberSamples",
                numberSamples,
                default=100)
            private$..makeMultipleBtn <- jmvcore::OptionAction$new(
                "makeMultipleBtn",
                makeMultipleBtn)
            private$..stopBtn <- jmvcore::OptionAction$new(
                "stopBtn",
                stopBtn)
            private$..inferVar1 <- jmvcore::OptionList$new(
                "inferVar1",
                inferVar1,
                options=list(
                    "rs",
                    "rp",
                    "re",
                    "p",
                    "n",
                    "blank1",
                    "sLLR",
                    "llknull",
                    "AIC",
                    "blank2",
                    "ws",
                    "wp",
                    "nw",
                    "blank3",
                    "ro",
                    "po",
                    "no"),
                default="rs")
            private$..inferVar2 <- jmvcore::OptionList$new(
                "inferVar2",
                inferVar2,
                options=list(
                    "rs",
                    "rp",
                    "re",
                    "p",
                    "n",
                    "blank1",
                    "sLLR",
                    "llknull",
                    "AIC",
                    "blank2",
                    "ws",
                    "wp",
                    "nw",
                    "blank3",
                    "ro",
                    "po",
                    "no"),
                default="p")
            private$..showSampleType <- jmvcore::OptionList$new(
                "showSampleType",
                showSampleType,
                options=list(
                    "Basic",
                    "Variables",
                    "Sample",
                    "Describe",
                    "Infer",
                    "Likelihood"),
                default="Basic")
            private$..showInferDimension <- jmvcore::OptionList$new(
                "showInferDimension",
                showInferDimension,
                options=list(
                    "1D",
                    "2D"),
                default="1D")
            private$..reportInferStats <- jmvcore::OptionList$new(
                "reportInferStats",
                reportInferStats,
                options=list(
                    "Means",
                    "Medians"),
                default="Medians")
            private$..showMultipleParam <- jmvcore::OptionList$new(
                "showMultipleParam",
                showMultipleParam,
                options=list(
                    "Single",
                    "Basic",
                    "blank1",
                    "p(sig)",
                    "NHST",
                    "Inference",
                    "Source",
                    "blank2",
                    "SEM",
                    "blank3",
                    "DV",
                    "Residuals"),
                default="Basic")
            private$..showMultipleDimension <- jmvcore::OptionList$new(
                "showMultipleDimension",
                showMultipleDimension,
                options=list(
                    "1D",
                    "2D"),
                default="1D")
            private$..exploreNPointsH <- jmvcore::OptionNumber$new(
                "exploreNPointsH",
                exploreNPointsH,
                default=11)
            private$..exploreNPointsD <- jmvcore::OptionNumber$new(
                "exploreNPointsD",
                exploreNPointsD,
                default=11)
            private$..exploreNPointsA <- jmvcore::OptionNumber$new(
                "exploreNPointsA",
                exploreNPointsA,
                default=11)
            private$..exploreNPointsM <- jmvcore::OptionNumber$new(
                "exploreNPointsM",
                exploreNPointsM,
                default=11)
            private$..exploreMinValH <- jmvcore::OptionString$new(
                "exploreMinValH",
                exploreMinValH,
                default="-0.9")
            private$..exploreMaxValH <- jmvcore::OptionString$new(
                "exploreMaxValH",
                exploreMaxValH,
                default="0.9")
            private$..exploreMinValD <- jmvcore::OptionString$new(
                "exploreMinValD",
                exploreMinValD,
                default="10")
            private$..exploreMaxValD <- jmvcore::OptionString$new(
                "exploreMaxValD",
                exploreMaxValD,
                default="250")
            private$..exploreMinValA <- jmvcore::OptionString$new(
                "exploreMinValA",
                exploreMinValA,
                default="0.001")
            private$..exploreMaxValM <- jmvcore::OptionString$new(
                "exploreMaxValM",
                exploreMaxValM,
                default="0.5")
            private$..exploreMinValM <- jmvcore::OptionString$new(
                "exploreMinValM",
                exploreMinValM,
                default="0.001")
            private$..exploreMaxValA <- jmvcore::OptionString$new(
                "exploreMaxValA",
                exploreMaxValA,
                default="0.5")
            private$..exploreXLogH <- jmvcore::OptionBool$new(
                "exploreXLogH",
                exploreXLogH,
                default=FALSE)
            private$..exploreXLogD <- jmvcore::OptionBool$new(
                "exploreXLogD",
                exploreXLogD,
                default=FALSE)
            private$..exploreXLogA <- jmvcore::OptionBool$new(
                "exploreXLogA",
                exploreXLogA,
                default=FALSE)
            private$..exploreXLogM <- jmvcore::OptionBool$new(
                "exploreXLogM",
                exploreXLogM,
                default=FALSE)
            private$..numberExplores <- jmvcore::OptionNumber$new(
                "numberExplores",
                numberExplores,
                default=10)
            private$..makeExploreBtn <- jmvcore::OptionAction$new(
                "makeExploreBtn",
                makeExploreBtn)
            private$..exploreMode <- jmvcore::OptionList$new(
                "exploreMode",
                exploreMode,
                options=list(
                    "hypothesisExplore",
                    "designExplore",
                    "analysisExplore",
                    "moreExplore"),
                default="designExplore")
            private$..hypothesisExploreList <- jmvcore::OptionList$new(
                "hypothesisExploreList",
                hypothesisExploreList,
                options=list(
                    "rIV",
                    "rIVIV2",
                    "rIVIV2DV",
                    "rSD",
                    "Heteroscedasticity",
                    "blank0h",
                    "IVType",
                    "IVskew",
                    "IVkurtosis",
                    "IVlevels",
                    "IVcats",
                    "IVprops",
                    "DVType",
                    "DVskew",
                    "DVkurtosis",
                    "DVcats",
                    "DVprops",
                    "blank1h",
                    "PDF",
                    "PDFk",
                    "PDFshape",
                    "blank2h",
                    "meanRplus",
                    "pRplus"))
            private$..designExploreList <- jmvcore::OptionList$new(
                "designExploreList",
                designExploreList,
                options=list(
                    "n",
                    "Method",
                    "Usage",
                    "NoSplits",
                    "blank1d",
                    "PoorSamplingAmount",
                    "Dependence",
                    "Outliers",
                    "NonResponse",
                    "IVRangeC",
                    "IVRangeE",
                    "blank1e",
                    "Cheating",
                    "CheatingAmount",
                    "blank1f",
                    "SampleSD"))
            private$..analysisExploreList <- jmvcore::OptionList$new(
                "analysisExploreList",
                analysisExploreList,
                options=list(
                    "Alpha",
                    "minRp",
                    "Transform",
                    "Welch",
                    "InteractionOn"))
            private$..moreExploreList <- jmvcore::OptionList$new(
                "moreExploreList",
                moreExploreList,
                options=list(
                    "Power",
                    "Keep",
                    "Repeats",
                    "blank1",
                    "NoStudies",
                    "MetaType"))
            private$..showExploreParam <- jmvcore::OptionList$new(
                "showExploreParam",
                showExploreParam,
                options=list(
                    "Single",
                    "Basic",
                    "blank1",
                    "p(sig)",
                    "n(sig)",
                    "NHST",
                    "Inference",
                    "Source",
                    "blank2",
                    "SEM",
                    "blank3",
                    "DV",
                    "Residuals"),
                default="Basic")
            private$..showExploreStyle <- jmvcore::OptionList$new(
                "showExploreStyle",
                showExploreStyle,
                options=list(
                    "stats",
                    "hist"),
                default="stats")
            private$..whichShowMultiple <- jmvcore::OptionList$new(
                "whichShowMultiple",
                whichShowMultiple,
                options=list(
                    "direct",
                    "unique",
                    "total",
                    "all"),
                default="all")
            private$..sendSample <- jmvcore::OptionOutput$new(
                "sendSample")
            private$..sendSamplewide <- jmvcore::OptionOutput$new(
                "sendSamplewide")
            private$..sendMultiple <- jmvcore::OptionOutput$new(
                "sendMultiple")
            private$..sendExplore <- jmvcore::OptionOutput$new(
                "sendExplore")
            private$..brawHelp <- jmvcore::OptionBool$new(
                "brawHelp",
                brawHelp,
                default=FALSE)
            private$..showHistory <- jmvcore::OptionBool$new(
                "showHistory",
                showHistory,
                default=TRUE)
            private$..showGraphs <- jmvcore::OptionList$new(
                "showGraphs",
                showGraphs,
                options=list(
                    "HTML",
                    "ggplot",
                    "none"),
                default="HTML")
            private$..fixedAxes <- jmvcore::OptionBool$new(
                "fixedAxes",
                fixedAxes,
                default=FALSE)
            private$..shorthandCalculations <- jmvcore::OptionBool$new(
                "shorthandCalculations",
                shorthandCalculations,
                default=FALSE)
            private$..dispRZ <- jmvcore::OptionList$new(
                "dispRZ",
                dispRZ,
                options=list(
                    "r",
                    "z"),
                default="r")
            private$..simGoBack <- jmvcore::OptionAction$new(
                "simGoBack",
                simGoBack)
            private$..simGoForwards <- jmvcore::OptionAction$new(
                "simGoForwards",
                simGoForwards)

            self$.addOption(private$..topMode)
            self$.addOption(private$..simPlanHelp)
            self$.addOption(private$..simSingleHelp)
            self$.addOption(private$..simMultipleHelp)
            self$.addOption(private$..simExploreHelp)
            self$.addOption(private$..planMode)
            self$.addOption(private$..presetDV)
            self$.addOption(private$..presetIV)
            self$.addOption(private$..presetIV2)
            self$.addOption(private$..DVname)
            self$.addOption(private$..DVtype)
            self$.addOption(private$..DVmu)
            self$.addOption(private$..DVsd)
            self$.addOption(private$..DVskew)
            self$.addOption(private$..DVkurt)
            self$.addOption(private$..DVnlevs)
            self$.addOption(private$..DViqr)
            self$.addOption(private$..DVncats)
            self$.addOption(private$..DVcases)
            self$.addOption(private$..DVprops)
            self$.addOption(private$..IVname)
            self$.addOption(private$..IVtype)
            self$.addOption(private$..IVmu)
            self$.addOption(private$..IVsd)
            self$.addOption(private$..IVskew)
            self$.addOption(private$..IVkurt)
            self$.addOption(private$..IVnlevs)
            self$.addOption(private$..IViqr)
            self$.addOption(private$..IVncats)
            self$.addOption(private$..IVcases)
            self$.addOption(private$..IVprops)
            self$.addOption(private$..IV2name)
            self$.addOption(private$..IV2type)
            self$.addOption(private$..IV2mu)
            self$.addOption(private$..IV2sd)
            self$.addOption(private$..IV2skew)
            self$.addOption(private$..IV2kurt)
            self$.addOption(private$..IV2nlevs)
            self$.addOption(private$..IV2iqr)
            self$.addOption(private$..IV2ncats)
            self$.addOption(private$..IV2cases)
            self$.addOption(private$..IV2props)
            self$.addOption(private$..EffectSize1)
            self$.addOption(private$..EffectSize2)
            self$.addOption(private$..EffectSize3)
            self$.addOption(private$..EffectSize12)
            self$.addOption(private$..EffectConfig)
            self$.addOption(private$..rSD)
            self$.addOption(private$..Heteroscedasticity)
            self$.addOption(private$..Residuals)
            self$.addOption(private$..WorldOn)
            self$.addOption(private$..WorldPDF)
            self$.addOption(private$..WorldRZ)
            self$.addOption(private$..worldMeanRplus)
            self$.addOption(private$..WorldShape)
            self$.addOption(private$..worldPRnull)
            self$.addOption(private$..WorldSampleRs)
            self$.addOption(private$..WorldSampleN)
            self$.addOption(private$..WorldSample)
            self$.addOption(private$..SampleSize)
            self$.addOption(private$..SampleSizeDist)
            self$.addOption(private$..SampleSizeM)
            self$.addOption(private$..SampleSpreadOn)
            self$.addOption(private$..SampleSD)
            self$.addOption(private$..SampleMethod)
            self$.addOption(private$..PoorSamplingAmount)
            self$.addOption(private$..SampleUsage1)
            self$.addOption(private$..SampleUsage2)
            self$.addOption(private$..Dependence)
            self$.addOption(private$..Outliers)
            self$.addOption(private$..NonResponse)
            self$.addOption(private$..LimitRangeIV)
            self$.addOption(private$..RangeMinIV)
            self$.addOption(private$..RangeMaxIV)
            self$.addOption(private$..LimitRangeIV2)
            self$.addOption(private$..RangeMinIV2)
            self$.addOption(private$..RangeMaxIV2)
            self$.addOption(private$..Cheating)
            self$.addOption(private$..CheatingBudget)
            self$.addOption(private$..ReplicationOn)
            self$.addOption(private$..ReplicationPower)
            self$.addOption(private$..ReplicationPrior)
            self$.addOption(private$..ReplicationAttempts)
            self$.addOption(private$..ReplicationDecision)
            self$.addOption(private$..RepMaxN)
            self$.addOption(private$..ReplicationAlpha)
            self$.addOption(private$..STMethod)
            self$.addOption(private$..alphaSig)
            self$.addOption(private$..minRp)
            self$.addOption(private$..keepOnlySig)
            self$.addOption(private$..biasAmount)
            self$.addOption(private$..ssq)
            self$.addOption(private$..main1)
            self$.addOption(private$..main2)
            self$.addOption(private$..interaction)
            self$.addOption(private$..covariation)
            self$.addOption(private$..equalVar)
            self$.addOption(private$..Transform)
            self$.addOption(private$..likelihoodType)
            self$.addOption(private$..likelihoodCutaway)
            self$.addOption(private$..likelihoodUsePrior)
            self$.addOption(private$..priorPDF)
            self$.addOption(private$..priorRZ)
            self$.addOption(private$..priorMeanRplus)
            self$.addOption(private$..priorPRplus)
            self$.addOption(private$..useAIC)
            self$.addOption(private$..MetaAnalysisOn)
            self$.addOption(private$..MetaAnalysisType)
            self$.addOption(private$..MetaAnalysisDist)
            self$.addOption(private$..MetaAnalysisPrior)
            self$.addOption(private$..MetaAnalysisNulls)
            self$.addOption(private$..MetaAnalysisBias)
            self$.addOption(private$..MetaAnalysisNStudies)
            self$.addOption(private$..MetaAnalysisMethod)
            self$.addOption(private$..MetaAnalysisStudiesSig)
            self$.addOption(private$..metaVar1)
            self$.addOption(private$..metaVar2)
            self$.addOption(private$..makeSampleBtn)
            self$.addOption(private$..numberSamples)
            self$.addOption(private$..makeMultipleBtn)
            self$.addOption(private$..stopBtn)
            self$.addOption(private$..inferVar1)
            self$.addOption(private$..inferVar2)
            self$.addOption(private$..showSampleType)
            self$.addOption(private$..showInferDimension)
            self$.addOption(private$..reportInferStats)
            self$.addOption(private$..showMultipleParam)
            self$.addOption(private$..showMultipleDimension)
            self$.addOption(private$..exploreNPointsH)
            self$.addOption(private$..exploreNPointsD)
            self$.addOption(private$..exploreNPointsA)
            self$.addOption(private$..exploreNPointsM)
            self$.addOption(private$..exploreMinValH)
            self$.addOption(private$..exploreMaxValH)
            self$.addOption(private$..exploreMinValD)
            self$.addOption(private$..exploreMaxValD)
            self$.addOption(private$..exploreMinValA)
            self$.addOption(private$..exploreMaxValM)
            self$.addOption(private$..exploreMinValM)
            self$.addOption(private$..exploreMaxValA)
            self$.addOption(private$..exploreXLogH)
            self$.addOption(private$..exploreXLogD)
            self$.addOption(private$..exploreXLogA)
            self$.addOption(private$..exploreXLogM)
            self$.addOption(private$..numberExplores)
            self$.addOption(private$..makeExploreBtn)
            self$.addOption(private$..exploreMode)
            self$.addOption(private$..hypothesisExploreList)
            self$.addOption(private$..designExploreList)
            self$.addOption(private$..analysisExploreList)
            self$.addOption(private$..moreExploreList)
            self$.addOption(private$..showExploreParam)
            self$.addOption(private$..showExploreStyle)
            self$.addOption(private$..whichShowMultiple)
            self$.addOption(private$..sendSample)
            self$.addOption(private$..sendSamplewide)
            self$.addOption(private$..sendMultiple)
            self$.addOption(private$..sendExplore)
            self$.addOption(private$..brawHelp)
            self$.addOption(private$..showHistory)
            self$.addOption(private$..showGraphs)
            self$.addOption(private$..fixedAxes)
            self$.addOption(private$..shorthandCalculations)
            self$.addOption(private$..dispRZ)
            self$.addOption(private$..simGoBack)
            self$.addOption(private$..simGoForwards)
        }),
    active = list(
        topMode = function() private$..topMode$value,
        simPlanHelp = function() private$..simPlanHelp$value,
        simSingleHelp = function() private$..simSingleHelp$value,
        simMultipleHelp = function() private$..simMultipleHelp$value,
        simExploreHelp = function() private$..simExploreHelp$value,
        planMode = function() private$..planMode$value,
        presetDV = function() private$..presetDV$value,
        presetIV = function() private$..presetIV$value,
        presetIV2 = function() private$..presetIV2$value,
        DVname = function() private$..DVname$value,
        DVtype = function() private$..DVtype$value,
        DVmu = function() private$..DVmu$value,
        DVsd = function() private$..DVsd$value,
        DVskew = function() private$..DVskew$value,
        DVkurt = function() private$..DVkurt$value,
        DVnlevs = function() private$..DVnlevs$value,
        DViqr = function() private$..DViqr$value,
        DVncats = function() private$..DVncats$value,
        DVcases = function() private$..DVcases$value,
        DVprops = function() private$..DVprops$value,
        IVname = function() private$..IVname$value,
        IVtype = function() private$..IVtype$value,
        IVmu = function() private$..IVmu$value,
        IVsd = function() private$..IVsd$value,
        IVskew = function() private$..IVskew$value,
        IVkurt = function() private$..IVkurt$value,
        IVnlevs = function() private$..IVnlevs$value,
        IViqr = function() private$..IViqr$value,
        IVncats = function() private$..IVncats$value,
        IVcases = function() private$..IVcases$value,
        IVprops = function() private$..IVprops$value,
        IV2name = function() private$..IV2name$value,
        IV2type = function() private$..IV2type$value,
        IV2mu = function() private$..IV2mu$value,
        IV2sd = function() private$..IV2sd$value,
        IV2skew = function() private$..IV2skew$value,
        IV2kurt = function() private$..IV2kurt$value,
        IV2nlevs = function() private$..IV2nlevs$value,
        IV2iqr = function() private$..IV2iqr$value,
        IV2ncats = function() private$..IV2ncats$value,
        IV2cases = function() private$..IV2cases$value,
        IV2props = function() private$..IV2props$value,
        EffectSize1 = function() private$..EffectSize1$value,
        EffectSize2 = function() private$..EffectSize2$value,
        EffectSize3 = function() private$..EffectSize3$value,
        EffectSize12 = function() private$..EffectSize12$value,
        EffectConfig = function() private$..EffectConfig$value,
        rSD = function() private$..rSD$value,
        Heteroscedasticity = function() private$..Heteroscedasticity$value,
        Residuals = function() private$..Residuals$value,
        WorldOn = function() private$..WorldOn$value,
        WorldPDF = function() private$..WorldPDF$value,
        WorldRZ = function() private$..WorldRZ$value,
        worldMeanRplus = function() private$..worldMeanRplus$value,
        WorldShape = function() private$..WorldShape$value,
        worldPRnull = function() private$..worldPRnull$value,
        WorldSampleRs = function() private$..WorldSampleRs$value,
        WorldSampleN = function() private$..WorldSampleN$value,
        WorldSample = function() private$..WorldSample$value,
        SampleSize = function() private$..SampleSize$value,
        SampleSizeDist = function() private$..SampleSizeDist$value,
        SampleSizeM = function() private$..SampleSizeM$value,
        SampleSpreadOn = function() private$..SampleSpreadOn$value,
        SampleSD = function() private$..SampleSD$value,
        SampleMethod = function() private$..SampleMethod$value,
        PoorSamplingAmount = function() private$..PoorSamplingAmount$value,
        SampleUsage1 = function() private$..SampleUsage1$value,
        SampleUsage2 = function() private$..SampleUsage2$value,
        Dependence = function() private$..Dependence$value,
        Outliers = function() private$..Outliers$value,
        NonResponse = function() private$..NonResponse$value,
        LimitRangeIV = function() private$..LimitRangeIV$value,
        RangeMinIV = function() private$..RangeMinIV$value,
        RangeMaxIV = function() private$..RangeMaxIV$value,
        LimitRangeIV2 = function() private$..LimitRangeIV2$value,
        RangeMinIV2 = function() private$..RangeMinIV2$value,
        RangeMaxIV2 = function() private$..RangeMaxIV2$value,
        Cheating = function() private$..Cheating$value,
        CheatingBudget = function() private$..CheatingBudget$value,
        ReplicationOn = function() private$..ReplicationOn$value,
        ReplicationPower = function() private$..ReplicationPower$value,
        ReplicationPrior = function() private$..ReplicationPrior$value,
        ReplicationAttempts = function() private$..ReplicationAttempts$value,
        ReplicationDecision = function() private$..ReplicationDecision$value,
        RepMaxN = function() private$..RepMaxN$value,
        ReplicationAlpha = function() private$..ReplicationAlpha$value,
        STMethod = function() private$..STMethod$value,
        alphaSig = function() private$..alphaSig$value,
        minRp = function() private$..minRp$value,
        keepOnlySig = function() private$..keepOnlySig$value,
        biasAmount = function() private$..biasAmount$value,
        ssq = function() private$..ssq$value,
        main1 = function() private$..main1$value,
        main2 = function() private$..main2$value,
        interaction = function() private$..interaction$value,
        covariation = function() private$..covariation$value,
        equalVar = function() private$..equalVar$value,
        Transform = function() private$..Transform$value,
        likelihoodType = function() private$..likelihoodType$value,
        likelihoodCutaway = function() private$..likelihoodCutaway$value,
        likelihoodUsePrior = function() private$..likelihoodUsePrior$value,
        priorPDF = function() private$..priorPDF$value,
        priorRZ = function() private$..priorRZ$value,
        priorMeanRplus = function() private$..priorMeanRplus$value,
        priorPRplus = function() private$..priorPRplus$value,
        useAIC = function() private$..useAIC$value,
        MetaAnalysisOn = function() private$..MetaAnalysisOn$value,
        MetaAnalysisType = function() private$..MetaAnalysisType$value,
        MetaAnalysisDist = function() private$..MetaAnalysisDist$value,
        MetaAnalysisPrior = function() private$..MetaAnalysisPrior$value,
        MetaAnalysisNulls = function() private$..MetaAnalysisNulls$value,
        MetaAnalysisBias = function() private$..MetaAnalysisBias$value,
        MetaAnalysisNStudies = function() private$..MetaAnalysisNStudies$value,
        MetaAnalysisMethod = function() private$..MetaAnalysisMethod$value,
        MetaAnalysisStudiesSig = function() private$..MetaAnalysisStudiesSig$value,
        metaVar1 = function() private$..metaVar1$value,
        metaVar2 = function() private$..metaVar2$value,
        makeSampleBtn = function() private$..makeSampleBtn$value,
        numberSamples = function() private$..numberSamples$value,
        makeMultipleBtn = function() private$..makeMultipleBtn$value,
        stopBtn = function() private$..stopBtn$value,
        inferVar1 = function() private$..inferVar1$value,
        inferVar2 = function() private$..inferVar2$value,
        showSampleType = function() private$..showSampleType$value,
        showInferDimension = function() private$..showInferDimension$value,
        reportInferStats = function() private$..reportInferStats$value,
        showMultipleParam = function() private$..showMultipleParam$value,
        showMultipleDimension = function() private$..showMultipleDimension$value,
        exploreNPointsH = function() private$..exploreNPointsH$value,
        exploreNPointsD = function() private$..exploreNPointsD$value,
        exploreNPointsA = function() private$..exploreNPointsA$value,
        exploreNPointsM = function() private$..exploreNPointsM$value,
        exploreMinValH = function() private$..exploreMinValH$value,
        exploreMaxValH = function() private$..exploreMaxValH$value,
        exploreMinValD = function() private$..exploreMinValD$value,
        exploreMaxValD = function() private$..exploreMaxValD$value,
        exploreMinValA = function() private$..exploreMinValA$value,
        exploreMaxValM = function() private$..exploreMaxValM$value,
        exploreMinValM = function() private$..exploreMinValM$value,
        exploreMaxValA = function() private$..exploreMaxValA$value,
        exploreXLogH = function() private$..exploreXLogH$value,
        exploreXLogD = function() private$..exploreXLogD$value,
        exploreXLogA = function() private$..exploreXLogA$value,
        exploreXLogM = function() private$..exploreXLogM$value,
        numberExplores = function() private$..numberExplores$value,
        makeExploreBtn = function() private$..makeExploreBtn$value,
        exploreMode = function() private$..exploreMode$value,
        hypothesisExploreList = function() private$..hypothesisExploreList$value,
        designExploreList = function() private$..designExploreList$value,
        analysisExploreList = function() private$..analysisExploreList$value,
        moreExploreList = function() private$..moreExploreList$value,
        showExploreParam = function() private$..showExploreParam$value,
        showExploreStyle = function() private$..showExploreStyle$value,
        whichShowMultiple = function() private$..whichShowMultiple$value,
        sendSample = function() private$..sendSample$value,
        sendSamplewide = function() private$..sendSamplewide$value,
        sendMultiple = function() private$..sendMultiple$value,
        sendExplore = function() private$..sendExplore$value,
        brawHelp = function() private$..brawHelp$value,
        showHistory = function() private$..showHistory$value,
        showGraphs = function() private$..showGraphs$value,
        fixedAxes = function() private$..fixedAxes$value,
        shorthandCalculations = function() private$..shorthandCalculations$value,
        dispRZ = function() private$..dispRZ$value,
        simGoBack = function() private$..simGoBack$value,
        simGoForwards = function() private$..simGoForwards$value),
    private = list(
        ..topMode = NA,
        ..simPlanHelp = NA,
        ..simSingleHelp = NA,
        ..simMultipleHelp = NA,
        ..simExploreHelp = NA,
        ..planMode = NA,
        ..presetDV = NA,
        ..presetIV = NA,
        ..presetIV2 = NA,
        ..DVname = NA,
        ..DVtype = NA,
        ..DVmu = NA,
        ..DVsd = NA,
        ..DVskew = NA,
        ..DVkurt = NA,
        ..DVnlevs = NA,
        ..DViqr = NA,
        ..DVncats = NA,
        ..DVcases = NA,
        ..DVprops = NA,
        ..IVname = NA,
        ..IVtype = NA,
        ..IVmu = NA,
        ..IVsd = NA,
        ..IVskew = NA,
        ..IVkurt = NA,
        ..IVnlevs = NA,
        ..IViqr = NA,
        ..IVncats = NA,
        ..IVcases = NA,
        ..IVprops = NA,
        ..IV2name = NA,
        ..IV2type = NA,
        ..IV2mu = NA,
        ..IV2sd = NA,
        ..IV2skew = NA,
        ..IV2kurt = NA,
        ..IV2nlevs = NA,
        ..IV2iqr = NA,
        ..IV2ncats = NA,
        ..IV2cases = NA,
        ..IV2props = NA,
        ..EffectSize1 = NA,
        ..EffectSize2 = NA,
        ..EffectSize3 = NA,
        ..EffectSize12 = NA,
        ..EffectConfig = NA,
        ..rSD = NA,
        ..Heteroscedasticity = NA,
        ..Residuals = NA,
        ..WorldOn = NA,
        ..WorldPDF = NA,
        ..WorldRZ = NA,
        ..worldMeanRplus = NA,
        ..WorldShape = NA,
        ..worldPRnull = NA,
        ..WorldSampleRs = NA,
        ..WorldSampleN = NA,
        ..WorldSample = NA,
        ..SampleSize = NA,
        ..SampleSizeDist = NA,
        ..SampleSizeM = NA,
        ..SampleSpreadOn = NA,
        ..SampleSD = NA,
        ..SampleMethod = NA,
        ..PoorSamplingAmount = NA,
        ..SampleUsage1 = NA,
        ..SampleUsage2 = NA,
        ..Dependence = NA,
        ..Outliers = NA,
        ..NonResponse = NA,
        ..LimitRangeIV = NA,
        ..RangeMinIV = NA,
        ..RangeMaxIV = NA,
        ..LimitRangeIV2 = NA,
        ..RangeMinIV2 = NA,
        ..RangeMaxIV2 = NA,
        ..Cheating = NA,
        ..CheatingBudget = NA,
        ..ReplicationOn = NA,
        ..ReplicationPower = NA,
        ..ReplicationPrior = NA,
        ..ReplicationAttempts = NA,
        ..ReplicationDecision = NA,
        ..RepMaxN = NA,
        ..ReplicationAlpha = NA,
        ..STMethod = NA,
        ..alphaSig = NA,
        ..minRp = NA,
        ..keepOnlySig = NA,
        ..biasAmount = NA,
        ..ssq = NA,
        ..main1 = NA,
        ..main2 = NA,
        ..interaction = NA,
        ..covariation = NA,
        ..equalVar = NA,
        ..Transform = NA,
        ..likelihoodType = NA,
        ..likelihoodCutaway = NA,
        ..likelihoodUsePrior = NA,
        ..priorPDF = NA,
        ..priorRZ = NA,
        ..priorMeanRplus = NA,
        ..priorPRplus = NA,
        ..useAIC = NA,
        ..MetaAnalysisOn = NA,
        ..MetaAnalysisType = NA,
        ..MetaAnalysisDist = NA,
        ..MetaAnalysisPrior = NA,
        ..MetaAnalysisNulls = NA,
        ..MetaAnalysisBias = NA,
        ..MetaAnalysisNStudies = NA,
        ..MetaAnalysisMethod = NA,
        ..MetaAnalysisStudiesSig = NA,
        ..metaVar1 = NA,
        ..metaVar2 = NA,
        ..makeSampleBtn = NA,
        ..numberSamples = NA,
        ..makeMultipleBtn = NA,
        ..stopBtn = NA,
        ..inferVar1 = NA,
        ..inferVar2 = NA,
        ..showSampleType = NA,
        ..showInferDimension = NA,
        ..reportInferStats = NA,
        ..showMultipleParam = NA,
        ..showMultipleDimension = NA,
        ..exploreNPointsH = NA,
        ..exploreNPointsD = NA,
        ..exploreNPointsA = NA,
        ..exploreNPointsM = NA,
        ..exploreMinValH = NA,
        ..exploreMaxValH = NA,
        ..exploreMinValD = NA,
        ..exploreMaxValD = NA,
        ..exploreMinValA = NA,
        ..exploreMaxValM = NA,
        ..exploreMinValM = NA,
        ..exploreMaxValA = NA,
        ..exploreXLogH = NA,
        ..exploreXLogD = NA,
        ..exploreXLogA = NA,
        ..exploreXLogM = NA,
        ..numberExplores = NA,
        ..makeExploreBtn = NA,
        ..exploreMode = NA,
        ..hypothesisExploreList = NA,
        ..designExploreList = NA,
        ..analysisExploreList = NA,
        ..moreExploreList = NA,
        ..showExploreParam = NA,
        ..showExploreStyle = NA,
        ..whichShowMultiple = NA,
        ..sendSample = NA,
        ..sendSamplewide = NA,
        ..sendMultiple = NA,
        ..sendExplore = NA,
        ..brawHelp = NA,
        ..showHistory = NA,
        ..showGraphs = NA,
        ..fixedAxes = NA,
        ..shorthandCalculations = NA,
        ..dispRZ = NA,
        ..simGoBack = NA,
        ..simGoForwards = NA)
)

BrawSimResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSimResults",
    inherit = jmvcore::Group,
    active = list(
        simSystemHTML = function() private$.items[["simSystemHTML"]],
        debug = function() private$.items[["debug"]],
        simGraphHTML = function() private$.items[["simGraphHTML"]],
        simGraph = function() private$.items[["simGraph"]],
        simReport = function() private$.items[["simReport"]],
        sendSample = function() private$.items[["sendSample"]],
        sendSamplewide = function() private$.items[["sendSamplewide"]],
        sendMultiple = function() private$.items[["sendMultiple"]],
        sendExplore = function() private$.items[["sendExplore"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Run Simulations",
                refs=list(
                    "brawstats",
                    "book"))
            self$add(jmvcore::Html$new(
                options=options,
                name="simSystemHTML",
                visible=FALSE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="simGraphHTML",
                visible=TRUE,
                clearWith=NULL))
            self$add(jmvcore::Image$new(
                options=options,
                name="simGraph",
                title=" ",
                width=550,
                height=400,
                visible=FALSE,
                renderFun=".plotSimGraph",
                clearWith=list(
                    "makeSampleBtn",
                    "showSampleType",
                    "showInferParam",
                    "inferVar1",
                    "inferVar2",
                    "reportInferStats",
                    "showInferDimension",
                    "makeMultipleBtn",
                    "showMultipleParam",
                    "showMultipleDimension",
                    "makeExploreBtn",
                    "showExploreParam",
                    "showExploreDimension",
                    "showExploreStyle",
                    "whichShowMultiple",
                    "MetaAnalysisType",
                    "MetaAnalysisMethod",
                    "MetaAnalysisPrior",
                    "MetaAnalysisBias",
                    "MetaAnalysisNulls",
                    "simGoBack",
                    "simGoForwards")))
            self$add(jmvcore::Html$new(
                options=options,
                name="simReport",
                visible=FALSE))
            self$add(jmvcore::Output$new(
                options=options,
                name="sendSample",
                measureType="nominal",
                varTitle="Sample",
                items=4))
            self$add(jmvcore::Output$new(
                options=options,
                name="sendSamplewide",
                measureType="nominal",
                varTitle="Sample",
                items=4))
            self$add(jmvcore::Output$new(
                options=options,
                name="sendMultiple",
                measureType="continuous",
                varTitle="Mult",
                items=4))
            self$add(jmvcore::Output$new(
                options=options,
                name="sendExplore",
                measureType="continuous",
                varTitle="Explore",
                items=5))}))

BrawSimBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSimBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BrawStats",
                name = "BrawSim",
                version = c(1,0,0),
                options = options,
                results = BrawSimResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Run Simulations
#'
#' 
#' @param topMode .
#' @param simPlanHelp .
#' @param simSingleHelp .
#' @param simMultipleHelp .
#' @param simExploreHelp .
#' @param planMode .
#' @param presetDV .
#' @param presetIV .
#' @param presetIV2 .
#' @param DVname .
#' @param DVtype .
#' @param DVmu .
#' @param DVsd .
#' @param DVskew .
#' @param DVkurt .
#' @param DVnlevs .
#' @param DViqr .
#' @param DVncats .
#' @param DVcases .
#' @param DVprops .
#' @param IVname .
#' @param IVtype .
#' @param IVmu .
#' @param IVsd .
#' @param IVskew .
#' @param IVkurt .
#' @param IVnlevs .
#' @param IViqr .
#' @param IVncats .
#' @param IVcases .
#' @param IVprops .
#' @param IV2name .
#' @param IV2type .
#' @param IV2mu .
#' @param IV2sd .
#' @param IV2skew .
#' @param IV2kurt .
#' @param IV2nlevs .
#' @param IV2iqr .
#' @param IV2ncats .
#' @param IV2cases .
#' @param IV2props .
#' @param EffectSize1 .
#' @param EffectSize2 .
#' @param EffectSize3 .
#' @param EffectSize12 .
#' @param EffectConfig .
#' @param rSD .
#' @param Heteroscedasticity .
#' @param Residuals .
#' @param WorldOn .
#' @param WorldPDF .
#' @param WorldRZ .
#' @param worldMeanRplus .
#' @param WorldShape .
#' @param worldPRnull .
#' @param WorldSampleRs .
#' @param WorldSampleN .
#' @param WorldSample .
#' @param SampleSize .
#' @param SampleSizeDist .
#' @param SampleSizeM .
#' @param SampleSpreadOn .
#' @param SampleSD .
#' @param SampleMethod .
#' @param PoorSamplingAmount .
#' @param SampleUsage1 .
#' @param SampleUsage2 .
#' @param Dependence .
#' @param Outliers .
#' @param NonResponse .
#' @param LimitRangeIV .
#' @param RangeMinIV .
#' @param RangeMaxIV .
#' @param LimitRangeIV2 .
#' @param RangeMinIV2 .
#' @param RangeMaxIV2 .
#' @param Cheating .
#' @param CheatingBudget .
#' @param ReplicationOn .
#' @param ReplicationPower .
#' @param ReplicationPrior .
#' @param ReplicationAttempts .
#' @param ReplicationDecision .
#' @param RepMaxN .
#' @param ReplicationAlpha .
#' @param STMethod .
#' @param alphaSig .
#' @param minRp .
#' @param keepOnlySig .
#' @param biasAmount .
#' @param ssq .
#' @param main1 .
#' @param main2 .
#' @param interaction .
#' @param covariation .
#' @param equalVar .
#' @param Transform .
#' @param likelihoodType .
#' @param likelihoodCutaway .
#' @param likelihoodUsePrior .
#' @param priorPDF .
#' @param priorRZ .
#' @param priorMeanRplus .
#' @param priorPRplus .
#' @param useAIC .
#' @param MetaAnalysisOn .
#' @param MetaAnalysisType .
#' @param MetaAnalysisDist .
#' @param MetaAnalysisPrior .
#' @param MetaAnalysisNulls .
#' @param MetaAnalysisBias .
#' @param MetaAnalysisNStudies .
#' @param MetaAnalysisMethod .
#' @param MetaAnalysisStudiesSig .
#' @param metaVar1 .
#' @param metaVar2 .
#' @param makeSampleBtn .
#' @param numberSamples .
#' @param makeMultipleBtn .
#' @param stopBtn .
#' @param inferVar1 .
#' @param inferVar2 .
#' @param showSampleType .
#' @param showInferDimension .
#' @param reportInferStats .
#' @param showMultipleParam .
#' @param showMultipleDimension .
#' @param exploreNPointsH .
#' @param exploreNPointsD .
#' @param exploreNPointsA .
#' @param exploreNPointsM .
#' @param exploreMinValH .
#' @param exploreMaxValH .
#' @param exploreMinValD .
#' @param exploreMaxValD .
#' @param exploreMinValA .
#' @param exploreMaxValM .
#' @param exploreMinValM .
#' @param exploreMaxValA .
#' @param exploreXLogH .
#' @param exploreXLogD .
#' @param exploreXLogA .
#' @param exploreXLogM .
#' @param numberExplores .
#' @param makeExploreBtn .
#' @param exploreMode .
#' @param hypothesisExploreList .
#' @param designExploreList .
#' @param analysisExploreList .
#' @param moreExploreList .
#' @param showExploreParam .
#' @param showExploreStyle .
#' @param whichShowMultiple .
#' @param brawHelp .
#' @param showHistory .
#' @param showGraphs .
#' @param fixedAxes .
#' @param shorthandCalculations .
#' @param dispRZ .
#' @param simGoBack .
#' @param simGoForwards .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$simSystemHTML} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$simGraphHTML} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$simGraph} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$simReport} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$sendSample} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$sendSamplewide} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$sendMultiple} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$sendExplore} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' @export
BrawSim <- function(
    topMode,
    simPlanHelp,
    simSingleHelp,
    simMultipleHelp,
    simExploreHelp,
    planMode,
    presetDV = "DV",
    presetIV = "IV",
    presetIV2 = "none",
    DVname = "DV",
    DVtype = "Interval",
    DVmu = 0,
    DVsd = 1,
    DVskew = 0,
    DVkurt = 0,
    DVnlevs = 7,
    DViqr = 4,
    DVncats = 2,
    DVcases = "C1,C2",
    DVprops = "1,1",
    IVname = "IV",
    IVtype = "Interval",
    IVmu = 0,
    IVsd = 1,
    IVskew = 0,
    IVkurt = 0,
    IVnlevs = 7,
    IViqr = 4,
    IVncats = 2,
    IVcases = "C1,C2",
    IVprops = "1,1",
    IV2name = "IV2",
    IV2type = "Interval",
    IV2mu = 0,
    IV2sd = 1,
    IV2skew = 0,
    IV2kurt = 0,
    IV2nlevs = 7,
    IV2iqr = 4,
    IV2ncats = 2,
    IV2cases = "C1,C2",
    IV2props = "1,1",
    EffectSize1 = 0,
    EffectSize2 = 0,
    EffectSize3 = 0,
    EffectSize12 = 0,
    EffectConfig = "normal",
    rSD = 0,
    Heteroscedasticity = 0,
    Residuals = "normal",
    WorldOn = FALSE,
    WorldPDF = "Exp",
    WorldRZ = "z",
    worldMeanRplus = 0.3,
    WorldShape = 1,
    worldPRnull = 0.5,
    WorldSampleRs = 0,
    WorldSampleN = 42,
    WorldSample = "none",
    SampleSize = 42,
    SampleSizeDist = "Gamma",
    SampleSizeM = 52,
    SampleSpreadOn = FALSE,
    SampleSD = 33.3,
    SampleMethod = "Random",
    PoorSamplingAmount = 0.1,
    SampleUsage1 = "Between",
    SampleUsage2 = "Between",
    Dependence = 0,
    Outliers = 0,
    NonResponse = 0,
    LimitRangeIV = "no",
    RangeMinIV = -3,
    RangeMaxIV = 3,
    LimitRangeIV2 = "no",
    RangeMinIV2 = -3,
    RangeMaxIV2 = 3,
    Cheating = "None",
    CheatingBudget = 0.1,
    ReplicationOn = FALSE,
    ReplicationPower = 0.8,
    ReplicationPrior = "None",
    ReplicationAttempts = 1,
    ReplicationDecision = "Cautious",
    RepMaxN = 100000,
    ReplicationAlpha = 0.05,
    STMethod,
    alphaSig = 0.05,
    minRp = 0,
    keepOnlySig = "no",
    biasAmount = 1,
    ssq = "Type3",
    main1 = TRUE,
    main2 = TRUE,
    interaction = FALSE,
    covariation = FALSE,
    equalVar = "yes",
    Transform = "None",
    likelihoodType = "Populations",
    likelihoodCutaway = "cutaway",
    likelihoodUsePrior = "none",
    priorPDF = "Exp",
    priorRZ = "z",
    priorMeanRplus = 0.3,
    priorPRplus = 1,
    useAIC = "none",
    MetaAnalysisOn = FALSE,
    MetaAnalysisType = "random",
    MetaAnalysisDist = "Simple",
    MetaAnalysisPrior = "none",
    MetaAnalysisNulls = FALSE,
    MetaAnalysisBias = FALSE,
    MetaAnalysisNStudies = 20,
    MetaAnalysisMethod = "MLE",
    MetaAnalysisStudiesSig = "no",
    metaVar1 = "metaRiv",
    metaVar2 = "metaRsd",
    makeSampleBtn = FALSE,
    numberSamples = 100,
    makeMultipleBtn,
    stopBtn,
    inferVar1 = "rs",
    inferVar2 = "p",
    showSampleType = "Basic",
    showInferDimension = "1D",
    reportInferStats = "Medians",
    showMultipleParam = "Basic",
    showMultipleDimension = "1D",
    exploreNPointsH = 11,
    exploreNPointsD = 11,
    exploreNPointsA = 11,
    exploreNPointsM = 11,
    exploreMinValH = "-0.9",
    exploreMaxValH = "0.9",
    exploreMinValD = "10",
    exploreMaxValD = "250",
    exploreMinValA = "0.001",
    exploreMaxValM = "0.5",
    exploreMinValM = "0.001",
    exploreMaxValA = "0.5",
    exploreXLogH = FALSE,
    exploreXLogD = FALSE,
    exploreXLogA = FALSE,
    exploreXLogM = FALSE,
    numberExplores = 10,
    makeExploreBtn,
    exploreMode = "designExplore",
    hypothesisExploreList,
    designExploreList,
    analysisExploreList,
    moreExploreList,
    showExploreParam = "Basic",
    showExploreStyle = "stats",
    whichShowMultiple = "all",
    brawHelp = FALSE,
    showHistory = TRUE,
    showGraphs = "HTML",
    fixedAxes = FALSE,
    shorthandCalculations = FALSE,
    dispRZ = "r",
    simGoBack,
    simGoForwards) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("BrawSim requires jmvcore to be installed (restart may be required)")


    options <- BrawSimOptions$new(
        topMode = topMode,
        simPlanHelp = simPlanHelp,
        simSingleHelp = simSingleHelp,
        simMultipleHelp = simMultipleHelp,
        simExploreHelp = simExploreHelp,
        planMode = planMode,
        presetDV = presetDV,
        presetIV = presetIV,
        presetIV2 = presetIV2,
        DVname = DVname,
        DVtype = DVtype,
        DVmu = DVmu,
        DVsd = DVsd,
        DVskew = DVskew,
        DVkurt = DVkurt,
        DVnlevs = DVnlevs,
        DViqr = DViqr,
        DVncats = DVncats,
        DVcases = DVcases,
        DVprops = DVprops,
        IVname = IVname,
        IVtype = IVtype,
        IVmu = IVmu,
        IVsd = IVsd,
        IVskew = IVskew,
        IVkurt = IVkurt,
        IVnlevs = IVnlevs,
        IViqr = IViqr,
        IVncats = IVncats,
        IVcases = IVcases,
        IVprops = IVprops,
        IV2name = IV2name,
        IV2type = IV2type,
        IV2mu = IV2mu,
        IV2sd = IV2sd,
        IV2skew = IV2skew,
        IV2kurt = IV2kurt,
        IV2nlevs = IV2nlevs,
        IV2iqr = IV2iqr,
        IV2ncats = IV2ncats,
        IV2cases = IV2cases,
        IV2props = IV2props,
        EffectSize1 = EffectSize1,
        EffectSize2 = EffectSize2,
        EffectSize3 = EffectSize3,
        EffectSize12 = EffectSize12,
        EffectConfig = EffectConfig,
        rSD = rSD,
        Heteroscedasticity = Heteroscedasticity,
        Residuals = Residuals,
        WorldOn = WorldOn,
        WorldPDF = WorldPDF,
        WorldRZ = WorldRZ,
        worldMeanRplus = worldMeanRplus,
        WorldShape = WorldShape,
        worldPRnull = worldPRnull,
        WorldSampleRs = WorldSampleRs,
        WorldSampleN = WorldSampleN,
        WorldSample = WorldSample,
        SampleSize = SampleSize,
        SampleSizeDist = SampleSizeDist,
        SampleSizeM = SampleSizeM,
        SampleSpreadOn = SampleSpreadOn,
        SampleSD = SampleSD,
        SampleMethod = SampleMethod,
        PoorSamplingAmount = PoorSamplingAmount,
        SampleUsage1 = SampleUsage1,
        SampleUsage2 = SampleUsage2,
        Dependence = Dependence,
        Outliers = Outliers,
        NonResponse = NonResponse,
        LimitRangeIV = LimitRangeIV,
        RangeMinIV = RangeMinIV,
        RangeMaxIV = RangeMaxIV,
        LimitRangeIV2 = LimitRangeIV2,
        RangeMinIV2 = RangeMinIV2,
        RangeMaxIV2 = RangeMaxIV2,
        Cheating = Cheating,
        CheatingBudget = CheatingBudget,
        ReplicationOn = ReplicationOn,
        ReplicationPower = ReplicationPower,
        ReplicationPrior = ReplicationPrior,
        ReplicationAttempts = ReplicationAttempts,
        ReplicationDecision = ReplicationDecision,
        RepMaxN = RepMaxN,
        ReplicationAlpha = ReplicationAlpha,
        STMethod = STMethod,
        alphaSig = alphaSig,
        minRp = minRp,
        keepOnlySig = keepOnlySig,
        biasAmount = biasAmount,
        ssq = ssq,
        main1 = main1,
        main2 = main2,
        interaction = interaction,
        covariation = covariation,
        equalVar = equalVar,
        Transform = Transform,
        likelihoodType = likelihoodType,
        likelihoodCutaway = likelihoodCutaway,
        likelihoodUsePrior = likelihoodUsePrior,
        priorPDF = priorPDF,
        priorRZ = priorRZ,
        priorMeanRplus = priorMeanRplus,
        priorPRplus = priorPRplus,
        useAIC = useAIC,
        MetaAnalysisOn = MetaAnalysisOn,
        MetaAnalysisType = MetaAnalysisType,
        MetaAnalysisDist = MetaAnalysisDist,
        MetaAnalysisPrior = MetaAnalysisPrior,
        MetaAnalysisNulls = MetaAnalysisNulls,
        MetaAnalysisBias = MetaAnalysisBias,
        MetaAnalysisNStudies = MetaAnalysisNStudies,
        MetaAnalysisMethod = MetaAnalysisMethod,
        MetaAnalysisStudiesSig = MetaAnalysisStudiesSig,
        metaVar1 = metaVar1,
        metaVar2 = metaVar2,
        makeSampleBtn = makeSampleBtn,
        numberSamples = numberSamples,
        makeMultipleBtn = makeMultipleBtn,
        stopBtn = stopBtn,
        inferVar1 = inferVar1,
        inferVar2 = inferVar2,
        showSampleType = showSampleType,
        showInferDimension = showInferDimension,
        reportInferStats = reportInferStats,
        showMultipleParam = showMultipleParam,
        showMultipleDimension = showMultipleDimension,
        exploreNPointsH = exploreNPointsH,
        exploreNPointsD = exploreNPointsD,
        exploreNPointsA = exploreNPointsA,
        exploreNPointsM = exploreNPointsM,
        exploreMinValH = exploreMinValH,
        exploreMaxValH = exploreMaxValH,
        exploreMinValD = exploreMinValD,
        exploreMaxValD = exploreMaxValD,
        exploreMinValA = exploreMinValA,
        exploreMaxValM = exploreMaxValM,
        exploreMinValM = exploreMinValM,
        exploreMaxValA = exploreMaxValA,
        exploreXLogH = exploreXLogH,
        exploreXLogD = exploreXLogD,
        exploreXLogA = exploreXLogA,
        exploreXLogM = exploreXLogM,
        numberExplores = numberExplores,
        makeExploreBtn = makeExploreBtn,
        exploreMode = exploreMode,
        hypothesisExploreList = hypothesisExploreList,
        designExploreList = designExploreList,
        analysisExploreList = analysisExploreList,
        moreExploreList = moreExploreList,
        showExploreParam = showExploreParam,
        showExploreStyle = showExploreStyle,
        whichShowMultiple = whichShowMultiple,
        brawHelp = brawHelp,
        showHistory = showHistory,
        showGraphs = showGraphs,
        fixedAxes = fixedAxes,
        shorthandCalculations = shorthandCalculations,
        dispRZ = dispRZ,
        simGoBack = simGoBack,
        simGoForwards = simGoForwards)

    analysis <- BrawSimClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

