
# This file is automatically generated, you probably don't want to edit this

BrawBasicsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawBasicsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            topMode = NULL,
            showHistory = TRUE,
            alwaysDoLong = FALSE,
            showGraphs = "HTML",
            fixedAxes = FALSE,
            basics1Help = NULL,
            doBasics1IV = "Perfectionism",
            doBasics1DV = "ExamGrade",
            doBasics1ABtn = NULL,
            doBasics1BBtn = NULL,
            doBasics1CSampling = "Convenience",
            doBasics1COutliers = FALSE,
            doBasics1BSkew = 0,
            doBasics1BKurt = 0,
            doBasics1CBtn = NULL,
            doBasics1CSampleSize = 100,
            basics2Help = NULL,
            doBasics2EffectSize = 0.3,
            doBasics2SampleSize = 50,
            doBasics2ABtn = NULL,
            doBasics2BBtn = NULL,
            doBasics2CBtn = NULL,
            basics3Help = NULL,
            doBasics3EffectSize = 0.5,
            doBasics3SampleSize = 50,
            doBasics3ABtn = NULL,
            doBasics3BBtn = NULL,
            doBasics3CBtn = NULL,
            doBasics31ABtn = NULL,
            doBasics31BBtn = NULL,
            basics4Help = NULL,
            doBasics4EffectSize1 = 0.3,
            doBasics4EffectSize2 = -0.3,
            doBasics4SampleSize = 150,
            doBasics4ABtn = NULL,
            doBasics4AmBtn = NULL,
            doBasics4BBtn = NULL,
            doBasics4BmBtn = NULL,
            doBasics4CBtn = NULL,
            doBasics4CmBtn = NULL,
            doBasics41ABtn = NULL,
            doBasics41BBtn = NULL,
            basics5Help = NULL,
            doBasics5EffectSize1x2 = 0.5,
            doBasics5SampleSize = 450,
            doBasics5Main1 = TRUE,
            doBasics5Main2 = TRUE,
            doBasics5Interaction = FALSE,
            doBasics5ABtn = NULL,
            doBasics5AmBtn = NULL,
            doBasics5BBtn = NULL,
            doBasics5BmBtn = NULL,
            doBasics5CBtn = NULL,
            doBasics5CmBtn = NULL,
            basics6Help = NULL,
            doBasics6Covariation = 0.7,
            doBasics6SampleSize = 500,
            doBasics6Main1 = TRUE,
            doBasics6Main2 = FALSE,
            doBasics6ABtn = NULL,
            doBasics6AmBtn = NULL,
            doBasics6BBtn = NULL,
            doBasics6BmBtn = NULL,
            doBasics6CBtn = NULL,
            doBasics6CmBtn = NULL,
            basics7Help = NULL,
            doBasics7ABtn = NULL,
            doBasics7AmBtn = NULL,
            doBasics7BBtn = NULL,
            doBasics7BmBtn = NULL,
            basics8Help = NULL,
            doBasics8ABtn = NULL,
            doBasics8AmBtn = NULL,
            doBasics8BBtn = NULL,
            doBasics8BmBtn = NULL,
            doBasics8CBtn = NULL,
            doBasics8CmBtn = NULL,
            doBasics81ABtn = NULL,
            doBasics81BBtn = NULL, ...) {

            super$initialize(
                package="BrawStats",
                name="BrawBasics",
                requiresData=FALSE,
                ...)

            private$..topMode <- jmvcore::OptionList$new(
                "topMode",
                topMode,
                options=list(
                    "Basics",
                    "Settings"))
            private$..sendSample <- jmvcore::OptionOutput$new(
                "sendSample")
            private$..sendSamplewide <- jmvcore::OptionOutput$new(
                "sendSamplewide")
            private$..sendMultiple <- jmvcore::OptionOutput$new(
                "sendMultiple")
            private$..showHistory <- jmvcore::OptionBool$new(
                "showHistory",
                showHistory,
                default=TRUE)
            private$..alwaysDoLong <- jmvcore::OptionBool$new(
                "alwaysDoLong",
                alwaysDoLong,
                default=FALSE)
            private$..showGraphs <- jmvcore::OptionList$new(
                "showGraphs",
                showGraphs,
                options=list(
                    "HTML",
                    "ggplot",
                    "none"),
                default="HTML")
            private$..fixedAxes <- jmvcore::OptionBool$new(
                "fixedAxes",
                fixedAxes,
                default=FALSE)
            private$..basics1Help <- jmvcore::OptionAction$new(
                "basics1Help",
                basics1Help)
            private$..doBasics1IV <- jmvcore::OptionList$new(
                "doBasics1IV",
                doBasics1IV,
                options=list(
                    "IQ",
                    "Diligence",
                    "Perfectionism",
                    "Anxiety",
                    "Happiness",
                    "SelfConfidence",
                    "RiskTaking",
                    "Interesting",
                    "Musician",
                    "Smoker",
                    "RiskTaker",
                    "StudySubject",
                    "BirthOrder"),
                default="Perfectionism")
            private$..doBasics1DV <- jmvcore::OptionList$new(
                "doBasics1DV",
                doBasics1DV,
                options=list(
                    "ExamGrade",
                    "ExamPass"),
                default="ExamGrade")
            private$..doBasics1ABtn <- jmvcore::OptionAction$new(
                "doBasics1ABtn",
                doBasics1ABtn)
            private$..doBasics1BBtn <- jmvcore::OptionAction$new(
                "doBasics1BBtn",
                doBasics1BBtn)
            private$..doBasics1CSampling <- jmvcore::OptionList$new(
                "doBasics1CSampling",
                doBasics1CSampling,
                options=list(
                    "Random",
                    "Convenience"),
                default="Convenience")
            private$..doBasics1COutliers <- jmvcore::OptionBool$new(
                "doBasics1COutliers",
                doBasics1COutliers,
                default=FALSE)
            private$..doBasics1BSkew <- jmvcore::OptionNumber$new(
                "doBasics1BSkew",
                doBasics1BSkew,
                default=0,
                min=-1,
                max=1)
            private$..doBasics1BKurt <- jmvcore::OptionNumber$new(
                "doBasics1BKurt",
                doBasics1BKurt,
                default=0,
                min=-1,
                max=1)
            private$..doBasics1CBtn <- jmvcore::OptionAction$new(
                "doBasics1CBtn",
                doBasics1CBtn)
            private$..doBasics1CSampleSize <- jmvcore::OptionNumber$new(
                "doBasics1CSampleSize",
                doBasics1CSampleSize,
                default=100,
                min=10,
                max=50000)
            private$..basics2Help <- jmvcore::OptionAction$new(
                "basics2Help",
                basics2Help)
            private$..doBasics2EffectSize <- jmvcore::OptionNumber$new(
                "doBasics2EffectSize",
                doBasics2EffectSize,
                default=0.3,
                min=-0.95,
                max=0.95)
            private$..doBasics2SampleSize <- jmvcore::OptionNumber$new(
                "doBasics2SampleSize",
                doBasics2SampleSize,
                default=50,
                min=10,
                max=50000)
            private$..doBasics2ABtn <- jmvcore::OptionAction$new(
                "doBasics2ABtn",
                doBasics2ABtn)
            private$..doBasics2BBtn <- jmvcore::OptionAction$new(
                "doBasics2BBtn",
                doBasics2BBtn)
            private$..doBasics2CBtn <- jmvcore::OptionAction$new(
                "doBasics2CBtn",
                doBasics2CBtn)
            private$..basics3Help <- jmvcore::OptionAction$new(
                "basics3Help",
                basics3Help)
            private$..doBasics3EffectSize <- jmvcore::OptionNumber$new(
                "doBasics3EffectSize",
                doBasics3EffectSize,
                default=0.5,
                min=-0.95,
                max=0.95)
            private$..doBasics3SampleSize <- jmvcore::OptionNumber$new(
                "doBasics3SampleSize",
                doBasics3SampleSize,
                default=50,
                min=10,
                max=50000)
            private$..doBasics3ABtn <- jmvcore::OptionAction$new(
                "doBasics3ABtn",
                doBasics3ABtn)
            private$..doBasics3BBtn <- jmvcore::OptionAction$new(
                "doBasics3BBtn",
                doBasics3BBtn)
            private$..doBasics3CBtn <- jmvcore::OptionAction$new(
                "doBasics3CBtn",
                doBasics3CBtn)
            private$..doBasics31ABtn <- jmvcore::OptionAction$new(
                "doBasics31ABtn",
                doBasics31ABtn)
            private$..doBasics31BBtn <- jmvcore::OptionAction$new(
                "doBasics31BBtn",
                doBasics31BBtn)
            private$..basics4Help <- jmvcore::OptionAction$new(
                "basics4Help",
                basics4Help)
            private$..doBasics4EffectSize1 <- jmvcore::OptionNumber$new(
                "doBasics4EffectSize1",
                doBasics4EffectSize1,
                default=0.3,
                min=-0.95,
                max=0.95)
            private$..doBasics4EffectSize2 <- jmvcore::OptionNumber$new(
                "doBasics4EffectSize2",
                doBasics4EffectSize2,
                default=-0.3,
                min=-0.95,
                max=0.95)
            private$..doBasics4SampleSize <- jmvcore::OptionNumber$new(
                "doBasics4SampleSize",
                doBasics4SampleSize,
                default=150,
                min=10,
                max=50000)
            private$..doBasics4ABtn <- jmvcore::OptionAction$new(
                "doBasics4ABtn",
                doBasics4ABtn)
            private$..doBasics4AmBtn <- jmvcore::OptionAction$new(
                "doBasics4AmBtn",
                doBasics4AmBtn)
            private$..doBasics4BBtn <- jmvcore::OptionAction$new(
                "doBasics4BBtn",
                doBasics4BBtn)
            private$..doBasics4BmBtn <- jmvcore::OptionAction$new(
                "doBasics4BmBtn",
                doBasics4BmBtn)
            private$..doBasics4CBtn <- jmvcore::OptionAction$new(
                "doBasics4CBtn",
                doBasics4CBtn)
            private$..doBasics4CmBtn <- jmvcore::OptionAction$new(
                "doBasics4CmBtn",
                doBasics4CmBtn)
            private$..doBasics41ABtn <- jmvcore::OptionAction$new(
                "doBasics41ABtn",
                doBasics41ABtn)
            private$..doBasics41BBtn <- jmvcore::OptionAction$new(
                "doBasics41BBtn",
                doBasics41BBtn)
            private$..basics5Help <- jmvcore::OptionAction$new(
                "basics5Help",
                basics5Help)
            private$..doBasics5EffectSize1x2 <- jmvcore::OptionNumber$new(
                "doBasics5EffectSize1x2",
                doBasics5EffectSize1x2,
                default=0.5,
                min=-0.95,
                max=0.95)
            private$..doBasics5SampleSize <- jmvcore::OptionNumber$new(
                "doBasics5SampleSize",
                doBasics5SampleSize,
                default=450,
                min=10,
                max=50000)
            private$..doBasics5Main1 <- jmvcore::OptionBool$new(
                "doBasics5Main1",
                doBasics5Main1,
                default=TRUE)
            private$..doBasics5Main2 <- jmvcore::OptionBool$new(
                "doBasics5Main2",
                doBasics5Main2,
                default=TRUE)
            private$..doBasics5Interaction <- jmvcore::OptionBool$new(
                "doBasics5Interaction",
                doBasics5Interaction,
                default=FALSE)
            private$..doBasics5ABtn <- jmvcore::OptionAction$new(
                "doBasics5ABtn",
                doBasics5ABtn)
            private$..doBasics5AmBtn <- jmvcore::OptionAction$new(
                "doBasics5AmBtn",
                doBasics5AmBtn)
            private$..doBasics5BBtn <- jmvcore::OptionAction$new(
                "doBasics5BBtn",
                doBasics5BBtn)
            private$..doBasics5BmBtn <- jmvcore::OptionAction$new(
                "doBasics5BmBtn",
                doBasics5BmBtn)
            private$..doBasics5CBtn <- jmvcore::OptionAction$new(
                "doBasics5CBtn",
                doBasics5CBtn)
            private$..doBasics5CmBtn <- jmvcore::OptionAction$new(
                "doBasics5CmBtn",
                doBasics5CmBtn)
            private$..basics6Help <- jmvcore::OptionAction$new(
                "basics6Help",
                basics6Help)
            private$..doBasics6Covariation <- jmvcore::OptionNumber$new(
                "doBasics6Covariation",
                doBasics6Covariation,
                default=0.7,
                min=-0.95,
                max=0.95)
            private$..doBasics6SampleSize <- jmvcore::OptionNumber$new(
                "doBasics6SampleSize",
                doBasics6SampleSize,
                default=500,
                min=10,
                max=50000)
            private$..doBasics6Main1 <- jmvcore::OptionBool$new(
                "doBasics6Main1",
                doBasics6Main1,
                default=TRUE)
            private$..doBasics6Main2 <- jmvcore::OptionBool$new(
                "doBasics6Main2",
                doBasics6Main2,
                default=FALSE)
            private$..doBasics6ABtn <- jmvcore::OptionAction$new(
                "doBasics6ABtn",
                doBasics6ABtn)
            private$..doBasics6AmBtn <- jmvcore::OptionAction$new(
                "doBasics6AmBtn",
                doBasics6AmBtn)
            private$..doBasics6BBtn <- jmvcore::OptionAction$new(
                "doBasics6BBtn",
                doBasics6BBtn)
            private$..doBasics6BmBtn <- jmvcore::OptionAction$new(
                "doBasics6BmBtn",
                doBasics6BmBtn)
            private$..doBasics6CBtn <- jmvcore::OptionAction$new(
                "doBasics6CBtn",
                doBasics6CBtn)
            private$..doBasics6CmBtn <- jmvcore::OptionAction$new(
                "doBasics6CmBtn",
                doBasics6CmBtn)
            private$..basics7Help <- jmvcore::OptionAction$new(
                "basics7Help",
                basics7Help)
            private$..doBasics7ABtn <- jmvcore::OptionAction$new(
                "doBasics7ABtn",
                doBasics7ABtn)
            private$..doBasics7AmBtn <- jmvcore::OptionAction$new(
                "doBasics7AmBtn",
                doBasics7AmBtn)
            private$..doBasics7BBtn <- jmvcore::OptionAction$new(
                "doBasics7BBtn",
                doBasics7BBtn)
            private$..doBasics7BmBtn <- jmvcore::OptionAction$new(
                "doBasics7BmBtn",
                doBasics7BmBtn)
            private$..basics8Help <- jmvcore::OptionAction$new(
                "basics8Help",
                basics8Help)
            private$..doBasics8ABtn <- jmvcore::OptionAction$new(
                "doBasics8ABtn",
                doBasics8ABtn)
            private$..doBasics8AmBtn <- jmvcore::OptionAction$new(
                "doBasics8AmBtn",
                doBasics8AmBtn)
            private$..doBasics8BBtn <- jmvcore::OptionAction$new(
                "doBasics8BBtn",
                doBasics8BBtn)
            private$..doBasics8BmBtn <- jmvcore::OptionAction$new(
                "doBasics8BmBtn",
                doBasics8BmBtn)
            private$..doBasics8CBtn <- jmvcore::OptionAction$new(
                "doBasics8CBtn",
                doBasics8CBtn)
            private$..doBasics8CmBtn <- jmvcore::OptionAction$new(
                "doBasics8CmBtn",
                doBasics8CmBtn)
            private$..doBasics81ABtn <- jmvcore::OptionAction$new(
                "doBasics81ABtn",
                doBasics81ABtn)
            private$..doBasics81BBtn <- jmvcore::OptionAction$new(
                "doBasics81BBtn",
                doBasics81BBtn)

            self$.addOption(private$..topMode)
            self$.addOption(private$..sendSample)
            self$.addOption(private$..sendSamplewide)
            self$.addOption(private$..sendMultiple)
            self$.addOption(private$..showHistory)
            self$.addOption(private$..alwaysDoLong)
            self$.addOption(private$..showGraphs)
            self$.addOption(private$..fixedAxes)
            self$.addOption(private$..basics1Help)
            self$.addOption(private$..doBasics1IV)
            self$.addOption(private$..doBasics1DV)
            self$.addOption(private$..doBasics1ABtn)
            self$.addOption(private$..doBasics1BBtn)
            self$.addOption(private$..doBasics1CSampling)
            self$.addOption(private$..doBasics1COutliers)
            self$.addOption(private$..doBasics1BSkew)
            self$.addOption(private$..doBasics1BKurt)
            self$.addOption(private$..doBasics1CBtn)
            self$.addOption(private$..doBasics1CSampleSize)
            self$.addOption(private$..basics2Help)
            self$.addOption(private$..doBasics2EffectSize)
            self$.addOption(private$..doBasics2SampleSize)
            self$.addOption(private$..doBasics2ABtn)
            self$.addOption(private$..doBasics2BBtn)
            self$.addOption(private$..doBasics2CBtn)
            self$.addOption(private$..basics3Help)
            self$.addOption(private$..doBasics3EffectSize)
            self$.addOption(private$..doBasics3SampleSize)
            self$.addOption(private$..doBasics3ABtn)
            self$.addOption(private$..doBasics3BBtn)
            self$.addOption(private$..doBasics3CBtn)
            self$.addOption(private$..doBasics31ABtn)
            self$.addOption(private$..doBasics31BBtn)
            self$.addOption(private$..basics4Help)
            self$.addOption(private$..doBasics4EffectSize1)
            self$.addOption(private$..doBasics4EffectSize2)
            self$.addOption(private$..doBasics4SampleSize)
            self$.addOption(private$..doBasics4ABtn)
            self$.addOption(private$..doBasics4AmBtn)
            self$.addOption(private$..doBasics4BBtn)
            self$.addOption(private$..doBasics4BmBtn)
            self$.addOption(private$..doBasics4CBtn)
            self$.addOption(private$..doBasics4CmBtn)
            self$.addOption(private$..doBasics41ABtn)
            self$.addOption(private$..doBasics41BBtn)
            self$.addOption(private$..basics5Help)
            self$.addOption(private$..doBasics5EffectSize1x2)
            self$.addOption(private$..doBasics5SampleSize)
            self$.addOption(private$..doBasics5Main1)
            self$.addOption(private$..doBasics5Main2)
            self$.addOption(private$..doBasics5Interaction)
            self$.addOption(private$..doBasics5ABtn)
            self$.addOption(private$..doBasics5AmBtn)
            self$.addOption(private$..doBasics5BBtn)
            self$.addOption(private$..doBasics5BmBtn)
            self$.addOption(private$..doBasics5CBtn)
            self$.addOption(private$..doBasics5CmBtn)
            self$.addOption(private$..basics6Help)
            self$.addOption(private$..doBasics6Covariation)
            self$.addOption(private$..doBasics6SampleSize)
            self$.addOption(private$..doBasics6Main1)
            self$.addOption(private$..doBasics6Main2)
            self$.addOption(private$..doBasics6ABtn)
            self$.addOption(private$..doBasics6AmBtn)
            self$.addOption(private$..doBasics6BBtn)
            self$.addOption(private$..doBasics6BmBtn)
            self$.addOption(private$..doBasics6CBtn)
            self$.addOption(private$..doBasics6CmBtn)
            self$.addOption(private$..basics7Help)
            self$.addOption(private$..doBasics7ABtn)
            self$.addOption(private$..doBasics7AmBtn)
            self$.addOption(private$..doBasics7BBtn)
            self$.addOption(private$..doBasics7BmBtn)
            self$.addOption(private$..basics8Help)
            self$.addOption(private$..doBasics8ABtn)
            self$.addOption(private$..doBasics8AmBtn)
            self$.addOption(private$..doBasics8BBtn)
            self$.addOption(private$..doBasics8BmBtn)
            self$.addOption(private$..doBasics8CBtn)
            self$.addOption(private$..doBasics8CmBtn)
            self$.addOption(private$..doBasics81ABtn)
            self$.addOption(private$..doBasics81BBtn)
        }),
    active = list(
        topMode = function() private$..topMode$value,
        sendSample = function() private$..sendSample$value,
        sendSamplewide = function() private$..sendSamplewide$value,
        sendMultiple = function() private$..sendMultiple$value,
        showHistory = function() private$..showHistory$value,
        alwaysDoLong = function() private$..alwaysDoLong$value,
        showGraphs = function() private$..showGraphs$value,
        fixedAxes = function() private$..fixedAxes$value,
        basics1Help = function() private$..basics1Help$value,
        doBasics1IV = function() private$..doBasics1IV$value,
        doBasics1DV = function() private$..doBasics1DV$value,
        doBasics1ABtn = function() private$..doBasics1ABtn$value,
        doBasics1BBtn = function() private$..doBasics1BBtn$value,
        doBasics1CSampling = function() private$..doBasics1CSampling$value,
        doBasics1COutliers = function() private$..doBasics1COutliers$value,
        doBasics1BSkew = function() private$..doBasics1BSkew$value,
        doBasics1BKurt = function() private$..doBasics1BKurt$value,
        doBasics1CBtn = function() private$..doBasics1CBtn$value,
        doBasics1CSampleSize = function() private$..doBasics1CSampleSize$value,
        basics2Help = function() private$..basics2Help$value,
        doBasics2EffectSize = function() private$..doBasics2EffectSize$value,
        doBasics2SampleSize = function() private$..doBasics2SampleSize$value,
        doBasics2ABtn = function() private$..doBasics2ABtn$value,
        doBasics2BBtn = function() private$..doBasics2BBtn$value,
        doBasics2CBtn = function() private$..doBasics2CBtn$value,
        basics3Help = function() private$..basics3Help$value,
        doBasics3EffectSize = function() private$..doBasics3EffectSize$value,
        doBasics3SampleSize = function() private$..doBasics3SampleSize$value,
        doBasics3ABtn = function() private$..doBasics3ABtn$value,
        doBasics3BBtn = function() private$..doBasics3BBtn$value,
        doBasics3CBtn = function() private$..doBasics3CBtn$value,
        doBasics31ABtn = function() private$..doBasics31ABtn$value,
        doBasics31BBtn = function() private$..doBasics31BBtn$value,
        basics4Help = function() private$..basics4Help$value,
        doBasics4EffectSize1 = function() private$..doBasics4EffectSize1$value,
        doBasics4EffectSize2 = function() private$..doBasics4EffectSize2$value,
        doBasics4SampleSize = function() private$..doBasics4SampleSize$value,
        doBasics4ABtn = function() private$..doBasics4ABtn$value,
        doBasics4AmBtn = function() private$..doBasics4AmBtn$value,
        doBasics4BBtn = function() private$..doBasics4BBtn$value,
        doBasics4BmBtn = function() private$..doBasics4BmBtn$value,
        doBasics4CBtn = function() private$..doBasics4CBtn$value,
        doBasics4CmBtn = function() private$..doBasics4CmBtn$value,
        doBasics41ABtn = function() private$..doBasics41ABtn$value,
        doBasics41BBtn = function() private$..doBasics41BBtn$value,
        basics5Help = function() private$..basics5Help$value,
        doBasics5EffectSize1x2 = function() private$..doBasics5EffectSize1x2$value,
        doBasics5SampleSize = function() private$..doBasics5SampleSize$value,
        doBasics5Main1 = function() private$..doBasics5Main1$value,
        doBasics5Main2 = function() private$..doBasics5Main2$value,
        doBasics5Interaction = function() private$..doBasics5Interaction$value,
        doBasics5ABtn = function() private$..doBasics5ABtn$value,
        doBasics5AmBtn = function() private$..doBasics5AmBtn$value,
        doBasics5BBtn = function() private$..doBasics5BBtn$value,
        doBasics5BmBtn = function() private$..doBasics5BmBtn$value,
        doBasics5CBtn = function() private$..doBasics5CBtn$value,
        doBasics5CmBtn = function() private$..doBasics5CmBtn$value,
        basics6Help = function() private$..basics6Help$value,
        doBasics6Covariation = function() private$..doBasics6Covariation$value,
        doBasics6SampleSize = function() private$..doBasics6SampleSize$value,
        doBasics6Main1 = function() private$..doBasics6Main1$value,
        doBasics6Main2 = function() private$..doBasics6Main2$value,
        doBasics6ABtn = function() private$..doBasics6ABtn$value,
        doBasics6AmBtn = function() private$..doBasics6AmBtn$value,
        doBasics6BBtn = function() private$..doBasics6BBtn$value,
        doBasics6BmBtn = function() private$..doBasics6BmBtn$value,
        doBasics6CBtn = function() private$..doBasics6CBtn$value,
        doBasics6CmBtn = function() private$..doBasics6CmBtn$value,
        basics7Help = function() private$..basics7Help$value,
        doBasics7ABtn = function() private$..doBasics7ABtn$value,
        doBasics7AmBtn = function() private$..doBasics7AmBtn$value,
        doBasics7BBtn = function() private$..doBasics7BBtn$value,
        doBasics7BmBtn = function() private$..doBasics7BmBtn$value,
        basics8Help = function() private$..basics8Help$value,
        doBasics8ABtn = function() private$..doBasics8ABtn$value,
        doBasics8AmBtn = function() private$..doBasics8AmBtn$value,
        doBasics8BBtn = function() private$..doBasics8BBtn$value,
        doBasics8BmBtn = function() private$..doBasics8BmBtn$value,
        doBasics8CBtn = function() private$..doBasics8CBtn$value,
        doBasics8CmBtn = function() private$..doBasics8CmBtn$value,
        doBasics81ABtn = function() private$..doBasics81ABtn$value,
        doBasics81BBtn = function() private$..doBasics81BBtn$value),
    private = list(
        ..topMode = NA,
        ..sendSample = NA,
        ..sendSamplewide = NA,
        ..sendMultiple = NA,
        ..showHistory = NA,
        ..alwaysDoLong = NA,
        ..showGraphs = NA,
        ..fixedAxes = NA,
        ..basics1Help = NA,
        ..doBasics1IV = NA,
        ..doBasics1DV = NA,
        ..doBasics1ABtn = NA,
        ..doBasics1BBtn = NA,
        ..doBasics1CSampling = NA,
        ..doBasics1COutliers = NA,
        ..doBasics1BSkew = NA,
        ..doBasics1BKurt = NA,
        ..doBasics1CBtn = NA,
        ..doBasics1CSampleSize = NA,
        ..basics2Help = NA,
        ..doBasics2EffectSize = NA,
        ..doBasics2SampleSize = NA,
        ..doBasics2ABtn = NA,
        ..doBasics2BBtn = NA,
        ..doBasics2CBtn = NA,
        ..basics3Help = NA,
        ..doBasics3EffectSize = NA,
        ..doBasics3SampleSize = NA,
        ..doBasics3ABtn = NA,
        ..doBasics3BBtn = NA,
        ..doBasics3CBtn = NA,
        ..doBasics31ABtn = NA,
        ..doBasics31BBtn = NA,
        ..basics4Help = NA,
        ..doBasics4EffectSize1 = NA,
        ..doBasics4EffectSize2 = NA,
        ..doBasics4SampleSize = NA,
        ..doBasics4ABtn = NA,
        ..doBasics4AmBtn = NA,
        ..doBasics4BBtn = NA,
        ..doBasics4BmBtn = NA,
        ..doBasics4CBtn = NA,
        ..doBasics4CmBtn = NA,
        ..doBasics41ABtn = NA,
        ..doBasics41BBtn = NA,
        ..basics5Help = NA,
        ..doBasics5EffectSize1x2 = NA,
        ..doBasics5SampleSize = NA,
        ..doBasics5Main1 = NA,
        ..doBasics5Main2 = NA,
        ..doBasics5Interaction = NA,
        ..doBasics5ABtn = NA,
        ..doBasics5AmBtn = NA,
        ..doBasics5BBtn = NA,
        ..doBasics5BmBtn = NA,
        ..doBasics5CBtn = NA,
        ..doBasics5CmBtn = NA,
        ..basics6Help = NA,
        ..doBasics6Covariation = NA,
        ..doBasics6SampleSize = NA,
        ..doBasics6Main1 = NA,
        ..doBasics6Main2 = NA,
        ..doBasics6ABtn = NA,
        ..doBasics6AmBtn = NA,
        ..doBasics6BBtn = NA,
        ..doBasics6BmBtn = NA,
        ..doBasics6CBtn = NA,
        ..doBasics6CmBtn = NA,
        ..basics7Help = NA,
        ..doBasics7ABtn = NA,
        ..doBasics7AmBtn = NA,
        ..doBasics7BBtn = NA,
        ..doBasics7BmBtn = NA,
        ..basics8Help = NA,
        ..doBasics8ABtn = NA,
        ..doBasics8AmBtn = NA,
        ..doBasics8BBtn = NA,
        ..doBasics8BmBtn = NA,
        ..doBasics8CBtn = NA,
        ..doBasics8CmBtn = NA,
        ..doBasics81ABtn = NA,
        ..doBasics81BBtn = NA)
)

BrawBasicsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawBasicsResults",
    inherit = jmvcore::Group,
    active = list(
        simSystemHTML = function() private$.items[["simSystemHTML"]],
        debug = function() private$.items[["debug"]],
        simGraphHTML = function() private$.items[["simGraphHTML"]],
        simGraph = function() private$.items[["simGraph"]],
        simReport = function() private$.items[["simReport"]],
        sendSample = function() private$.items[["sendSample"]],
        sendSamplewide = function() private$.items[["sendSamplewide"]],
        sendMultiple = function() private$.items[["sendMultiple"]],
        sendExplore = function() private$.items[["sendExplore"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Learn Basics",
                refs=list(
                    "brawstats",
                    "book"))
            self$add(jmvcore::Html$new(
                options=options,
                name="simSystemHTML",
                visible=FALSE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="simGraphHTML",
                visible=TRUE,
                clearWith=NULL))
            self$add(jmvcore::Image$new(
                options=options,
                name="simGraph",
                title=" ",
                width=550,
                height=400,
                visible=FALSE,
                renderFun=".plotSimGraph",
                clearWith=list(
                    "makeSampleBtn",
                    "showSampleType",
                    "showInferParam",
                    "inferVar1",
                    "inferVar2",
                    "reportInferStats",
                    "showInferDimension",
                    "makeMultipleBtn",
                    "showMultipleParam",
                    "showMultipleDimension",
                    "makeExploreBtn",
                    "showExploreParam",
                    "showExploreDimension",
                    "showExploreStyle",
                    "whichShowMultiple",
                    "MetaAnalysisType",
                    "MetaAnalysisMethod",
                    "MetaAnalysisPrior",
                    "MetaAnalysisBias",
                    "MetaAnalysisNulls",
                    "simGoBack",
                    "simGoForwards")))
            self$add(jmvcore::Html$new(
                options=options,
                name="simReport",
                visible=FALSE))
            self$add(jmvcore::Output$new(
                options=options,
                name="sendSample",
                measureType="nominal",
                varTitle="Sample",
                items=4))
            self$add(jmvcore::Output$new(
                options=options,
                name="sendSamplewide",
                measureType="nominal",
                varTitle="Sample",
                items=4))
            self$add(jmvcore::Output$new(
                options=options,
                name="sendMultiple",
                measureType="continuous",
                varTitle="Mult",
                items=4))
            self$add(jmvcore::Output$new(
                options=options,
                name="sendExplore",
                measureType="continuous",
                varTitle="Explore",
                items=5))}))

BrawBasicsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawBasicsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BrawStats",
                name = "BrawBasics",
                version = c(1,0,0),
                options = options,
                results = BrawBasicsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Learn Basics
#'
#' 
#' @param topMode .
#' @param showHistory .
#' @param alwaysDoLong .
#' @param showGraphs .
#' @param fixedAxes .
#' @param basics1Help .
#' @param doBasics1IV .
#' @param doBasics1DV .
#' @param doBasics1ABtn .
#' @param doBasics1BBtn .
#' @param doBasics1CSampling .
#' @param doBasics1COutliers .
#' @param doBasics1BSkew .
#' @param doBasics1BKurt .
#' @param doBasics1CBtn .
#' @param doBasics1CSampleSize .
#' @param basics2Help .
#' @param doBasics2EffectSize .
#' @param doBasics2SampleSize .
#' @param doBasics2ABtn .
#' @param doBasics2BBtn .
#' @param doBasics2CBtn .
#' @param basics3Help .
#' @param doBasics3EffectSize .
#' @param doBasics3SampleSize .
#' @param doBasics3ABtn .
#' @param doBasics3BBtn .
#' @param doBasics3CBtn .
#' @param doBasics31ABtn .
#' @param doBasics31BBtn .
#' @param basics4Help .
#' @param doBasics4EffectSize1 .
#' @param doBasics4EffectSize2 .
#' @param doBasics4SampleSize .
#' @param doBasics4ABtn .
#' @param doBasics4AmBtn .
#' @param doBasics4BBtn .
#' @param doBasics4BmBtn .
#' @param doBasics4CBtn .
#' @param doBasics4CmBtn .
#' @param doBasics41ABtn .
#' @param doBasics41BBtn .
#' @param basics5Help .
#' @param doBasics5EffectSize1x2 .
#' @param doBasics5SampleSize .
#' @param doBasics5Main1 .
#' @param doBasics5Main2 .
#' @param doBasics5Interaction .
#' @param doBasics5ABtn .
#' @param doBasics5AmBtn .
#' @param doBasics5BBtn .
#' @param doBasics5BmBtn .
#' @param doBasics5CBtn .
#' @param doBasics5CmBtn .
#' @param basics6Help .
#' @param doBasics6Covariation .
#' @param doBasics6SampleSize .
#' @param doBasics6Main1 .
#' @param doBasics6Main2 .
#' @param doBasics6ABtn .
#' @param doBasics6AmBtn .
#' @param doBasics6BBtn .
#' @param doBasics6BmBtn .
#' @param doBasics6CBtn .
#' @param doBasics6CmBtn .
#' @param basics7Help .
#' @param doBasics7ABtn .
#' @param doBasics7AmBtn .
#' @param doBasics7BBtn .
#' @param doBasics7BmBtn .
#' @param basics8Help .
#' @param doBasics8ABtn .
#' @param doBasics8AmBtn .
#' @param doBasics8BBtn .
#' @param doBasics8BmBtn .
#' @param doBasics8CBtn .
#' @param doBasics8CmBtn .
#' @param doBasics81ABtn .
#' @param doBasics81BBtn .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$simSystemHTML} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$simGraphHTML} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$simGraph} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$simReport} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$sendSample} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$sendSamplewide} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$sendMultiple} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$sendExplore} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' @export
BrawBasics <- function(
    topMode,
    showHistory = TRUE,
    alwaysDoLong = FALSE,
    showGraphs = "HTML",
    fixedAxes = FALSE,
    basics1Help,
    doBasics1IV = "Perfectionism",
    doBasics1DV = "ExamGrade",
    doBasics1ABtn,
    doBasics1BBtn,
    doBasics1CSampling = "Convenience",
    doBasics1COutliers = FALSE,
    doBasics1BSkew = 0,
    doBasics1BKurt = 0,
    doBasics1CBtn,
    doBasics1CSampleSize = 100,
    basics2Help,
    doBasics2EffectSize = 0.3,
    doBasics2SampleSize = 50,
    doBasics2ABtn,
    doBasics2BBtn,
    doBasics2CBtn,
    basics3Help,
    doBasics3EffectSize = 0.5,
    doBasics3SampleSize = 50,
    doBasics3ABtn,
    doBasics3BBtn,
    doBasics3CBtn,
    doBasics31ABtn,
    doBasics31BBtn,
    basics4Help,
    doBasics4EffectSize1 = 0.3,
    doBasics4EffectSize2 = -0.3,
    doBasics4SampleSize = 150,
    doBasics4ABtn,
    doBasics4AmBtn,
    doBasics4BBtn,
    doBasics4BmBtn,
    doBasics4CBtn,
    doBasics4CmBtn,
    doBasics41ABtn,
    doBasics41BBtn,
    basics5Help,
    doBasics5EffectSize1x2 = 0.5,
    doBasics5SampleSize = 450,
    doBasics5Main1 = TRUE,
    doBasics5Main2 = TRUE,
    doBasics5Interaction = FALSE,
    doBasics5ABtn,
    doBasics5AmBtn,
    doBasics5BBtn,
    doBasics5BmBtn,
    doBasics5CBtn,
    doBasics5CmBtn,
    basics6Help,
    doBasics6Covariation = 0.7,
    doBasics6SampleSize = 500,
    doBasics6Main1 = TRUE,
    doBasics6Main2 = FALSE,
    doBasics6ABtn,
    doBasics6AmBtn,
    doBasics6BBtn,
    doBasics6BmBtn,
    doBasics6CBtn,
    doBasics6CmBtn,
    basics7Help,
    doBasics7ABtn,
    doBasics7AmBtn,
    doBasics7BBtn,
    doBasics7BmBtn,
    basics8Help,
    doBasics8ABtn,
    doBasics8AmBtn,
    doBasics8BBtn,
    doBasics8BmBtn,
    doBasics8CBtn,
    doBasics8CmBtn,
    doBasics81ABtn,
    doBasics81BBtn) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("BrawBasics requires jmvcore to be installed (restart may be required)")


    options <- BrawBasicsOptions$new(
        topMode = topMode,
        showHistory = showHistory,
        alwaysDoLong = alwaysDoLong,
        showGraphs = showGraphs,
        fixedAxes = fixedAxes,
        basics1Help = basics1Help,
        doBasics1IV = doBasics1IV,
        doBasics1DV = doBasics1DV,
        doBasics1ABtn = doBasics1ABtn,
        doBasics1BBtn = doBasics1BBtn,
        doBasics1CSampling = doBasics1CSampling,
        doBasics1COutliers = doBasics1COutliers,
        doBasics1BSkew = doBasics1BSkew,
        doBasics1BKurt = doBasics1BKurt,
        doBasics1CBtn = doBasics1CBtn,
        doBasics1CSampleSize = doBasics1CSampleSize,
        basics2Help = basics2Help,
        doBasics2EffectSize = doBasics2EffectSize,
        doBasics2SampleSize = doBasics2SampleSize,
        doBasics2ABtn = doBasics2ABtn,
        doBasics2BBtn = doBasics2BBtn,
        doBasics2CBtn = doBasics2CBtn,
        basics3Help = basics3Help,
        doBasics3EffectSize = doBasics3EffectSize,
        doBasics3SampleSize = doBasics3SampleSize,
        doBasics3ABtn = doBasics3ABtn,
        doBasics3BBtn = doBasics3BBtn,
        doBasics3CBtn = doBasics3CBtn,
        doBasics31ABtn = doBasics31ABtn,
        doBasics31BBtn = doBasics31BBtn,
        basics4Help = basics4Help,
        doBasics4EffectSize1 = doBasics4EffectSize1,
        doBasics4EffectSize2 = doBasics4EffectSize2,
        doBasics4SampleSize = doBasics4SampleSize,
        doBasics4ABtn = doBasics4ABtn,
        doBasics4AmBtn = doBasics4AmBtn,
        doBasics4BBtn = doBasics4BBtn,
        doBasics4BmBtn = doBasics4BmBtn,
        doBasics4CBtn = doBasics4CBtn,
        doBasics4CmBtn = doBasics4CmBtn,
        doBasics41ABtn = doBasics41ABtn,
        doBasics41BBtn = doBasics41BBtn,
        basics5Help = basics5Help,
        doBasics5EffectSize1x2 = doBasics5EffectSize1x2,
        doBasics5SampleSize = doBasics5SampleSize,
        doBasics5Main1 = doBasics5Main1,
        doBasics5Main2 = doBasics5Main2,
        doBasics5Interaction = doBasics5Interaction,
        doBasics5ABtn = doBasics5ABtn,
        doBasics5AmBtn = doBasics5AmBtn,
        doBasics5BBtn = doBasics5BBtn,
        doBasics5BmBtn = doBasics5BmBtn,
        doBasics5CBtn = doBasics5CBtn,
        doBasics5CmBtn = doBasics5CmBtn,
        basics6Help = basics6Help,
        doBasics6Covariation = doBasics6Covariation,
        doBasics6SampleSize = doBasics6SampleSize,
        doBasics6Main1 = doBasics6Main1,
        doBasics6Main2 = doBasics6Main2,
        doBasics6ABtn = doBasics6ABtn,
        doBasics6AmBtn = doBasics6AmBtn,
        doBasics6BBtn = doBasics6BBtn,
        doBasics6BmBtn = doBasics6BmBtn,
        doBasics6CBtn = doBasics6CBtn,
        doBasics6CmBtn = doBasics6CmBtn,
        basics7Help = basics7Help,
        doBasics7ABtn = doBasics7ABtn,
        doBasics7AmBtn = doBasics7AmBtn,
        doBasics7BBtn = doBasics7BBtn,
        doBasics7BmBtn = doBasics7BmBtn,
        basics8Help = basics8Help,
        doBasics8ABtn = doBasics8ABtn,
        doBasics8AmBtn = doBasics8AmBtn,
        doBasics8BBtn = doBasics8BBtn,
        doBasics8BmBtn = doBasics8BmBtn,
        doBasics8CBtn = doBasics8CBtn,
        doBasics8CmBtn = doBasics8CmBtn,
        doBasics81ABtn = doBasics81ABtn,
        doBasics81BBtn = doBasics81BBtn)

    analysis <- BrawBasicsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

