
# This file is automatically generated, you probably don't want to edit this

BrawANOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawANOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            analysisMode = NULL,
            IV = NULL,
            DV = NULL,
            inferWhich = "r",
            whichR = "Direct",
            Stage5 = NULL,
            Stage4 = NULL,
            Stage3 = NULL,
            Stage2 = NULL,
            Stage1 = NULL,
            Stage5On = TRUE,
            Stage4On = TRUE,
            Stage3On = TRUE,
            Stage2On = TRUE,
            Stage1On = TRUE,
            causalDirection = "down",
            Depth = "d1",
            ShowType = "ES",
            clearHistory = NULL,
            addDest = NULL,
            addSource = NULL,
            removeDest = NULL,
            removeSource = NULL,
            onlySource = NULL,
            onlyDest = NULL, ...) {

            super$initialize(
                package="BrawStats",
                name="BrawAN",
                requiresData=TRUE,
                ...)

            private$..analysisMode <- jmvcore::OptionList$new(
                "analysisMode",
                analysisMode,
                options=list(
                    "AnalyseData",
                    "LinearModel",
                    "PathModel"))
            private$..IV <- jmvcore::OptionVariables$new(
                "IV",
                IV)
            private$..DV <- jmvcore::OptionVariable$new(
                "DV",
                DV)
            private$..inferWhich <- jmvcore::OptionList$new(
                "inferWhich",
                inferWhich,
                options=list(
                    "r",
                    "p"),
                default="r")
            private$..whichR <- jmvcore::OptionList$new(
                "whichR",
                whichR,
                options=list(
                    "Direct",
                    "Unique",
                    "Total",
                    "Full"),
                default="Direct")
            private$..Stage5 <- jmvcore::OptionVariables$new(
                "Stage5",
                Stage5)
            private$..Stage4 <- jmvcore::OptionVariables$new(
                "Stage4",
                Stage4)
            private$..Stage3 <- jmvcore::OptionVariables$new(
                "Stage3",
                Stage3)
            private$..Stage2 <- jmvcore::OptionVariables$new(
                "Stage2",
                Stage2)
            private$..Stage1 <- jmvcore::OptionVariables$new(
                "Stage1",
                Stage1)
            private$..Stage5On <- jmvcore::OptionBool$new(
                "Stage5On",
                Stage5On,
                default=TRUE)
            private$..Stage4On <- jmvcore::OptionBool$new(
                "Stage4On",
                Stage4On,
                default=TRUE)
            private$..Stage3On <- jmvcore::OptionBool$new(
                "Stage3On",
                Stage3On,
                default=TRUE)
            private$..Stage2On <- jmvcore::OptionBool$new(
                "Stage2On",
                Stage2On,
                default=TRUE)
            private$..Stage1On <- jmvcore::OptionBool$new(
                "Stage1On",
                Stage1On,
                default=TRUE)
            private$..causalDirection <- jmvcore::OptionList$new(
                "causalDirection",
                causalDirection,
                options=list(
                    "up",
                    "down"),
                default="down")
            private$..Depth <- jmvcore::OptionList$new(
                "Depth",
                Depth,
                options=list(
                    "d1",
                    "d2",
                    "all"),
                default="d1")
            private$..ShowType <- jmvcore::OptionList$new(
                "ShowType",
                ShowType,
                options=list(
                    "CF",
                    "ES",
                    "cov"),
                default="ES")
            private$..clearHistory <- jmvcore::OptionAction$new(
                "clearHistory",
                clearHistory)
            private$..addDest <- jmvcore::OptionVariables$new(
                "addDest",
                addDest)
            private$..addSource <- jmvcore::OptionVariables$new(
                "addSource",
                addSource)
            private$..removeDest <- jmvcore::OptionVariables$new(
                "removeDest",
                removeDest)
            private$..removeSource <- jmvcore::OptionVariables$new(
                "removeSource",
                removeSource)
            private$..onlySource <- jmvcore::OptionVariables$new(
                "onlySource",
                onlySource)
            private$..onlyDest <- jmvcore::OptionVariables$new(
                "onlyDest",
                onlyDest)

            self$.addOption(private$..analysisMode)
            self$.addOption(private$..IV)
            self$.addOption(private$..DV)
            self$.addOption(private$..inferWhich)
            self$.addOption(private$..whichR)
            self$.addOption(private$..Stage5)
            self$.addOption(private$..Stage4)
            self$.addOption(private$..Stage3)
            self$.addOption(private$..Stage2)
            self$.addOption(private$..Stage1)
            self$.addOption(private$..Stage5On)
            self$.addOption(private$..Stage4On)
            self$.addOption(private$..Stage3On)
            self$.addOption(private$..Stage2On)
            self$.addOption(private$..Stage1On)
            self$.addOption(private$..causalDirection)
            self$.addOption(private$..Depth)
            self$.addOption(private$..ShowType)
            self$.addOption(private$..clearHistory)
            self$.addOption(private$..addDest)
            self$.addOption(private$..addSource)
            self$.addOption(private$..removeDest)
            self$.addOption(private$..removeSource)
            self$.addOption(private$..onlySource)
            self$.addOption(private$..onlyDest)
        }),
    active = list(
        analysisMode = function() private$..analysisMode$value,
        IV = function() private$..IV$value,
        DV = function() private$..DV$value,
        inferWhich = function() private$..inferWhich$value,
        whichR = function() private$..whichR$value,
        Stage5 = function() private$..Stage5$value,
        Stage4 = function() private$..Stage4$value,
        Stage3 = function() private$..Stage3$value,
        Stage2 = function() private$..Stage2$value,
        Stage1 = function() private$..Stage1$value,
        Stage5On = function() private$..Stage5On$value,
        Stage4On = function() private$..Stage4On$value,
        Stage3On = function() private$..Stage3On$value,
        Stage2On = function() private$..Stage2On$value,
        Stage1On = function() private$..Stage1On$value,
        causalDirection = function() private$..causalDirection$value,
        Depth = function() private$..Depth$value,
        ShowType = function() private$..ShowType$value,
        clearHistory = function() private$..clearHistory$value,
        addDest = function() private$..addDest$value,
        addSource = function() private$..addSource$value,
        removeDest = function() private$..removeDest$value,
        removeSource = function() private$..removeSource$value,
        onlySource = function() private$..onlySource$value,
        onlyDest = function() private$..onlyDest$value),
    private = list(
        ..analysisMode = NA,
        ..IV = NA,
        ..DV = NA,
        ..inferWhich = NA,
        ..whichR = NA,
        ..Stage5 = NA,
        ..Stage4 = NA,
        ..Stage3 = NA,
        ..Stage2 = NA,
        ..Stage1 = NA,
        ..Stage5On = NA,
        ..Stage4On = NA,
        ..Stage3On = NA,
        ..Stage2On = NA,
        ..Stage1On = NA,
        ..causalDirection = NA,
        ..Depth = NA,
        ..ShowType = NA,
        ..clearHistory = NA,
        ..addDest = NA,
        ..addSource = NA,
        ..removeDest = NA,
        ..removeSource = NA,
        ..onlySource = NA,
        ..onlyDest = NA)
)

BrawANResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawANResults",
    inherit = jmvcore::Group,
    active = list(
        lmGraph = function() private$.items[["lmGraph"]],
        lmReport = function() private$.items[["lmReport"]],
        semGraph = function() private$.items[["semGraph"]],
        semReport = function() private$.items[["semReport"]],
        debug = function() private$.items[["debug"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Analyse Data")
            self$add(jmvcore::Image$new(
                options=options,
                name="lmGraph",
                title=" ",
                width=500,
                height=300,
                renderFun=".lmPlotGraph",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="lmReport",
                title=" ",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="semGraph",
                title=" ",
                width=500,
                height=300,
                renderFun=".semPlotGraph",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="semReport",
                title=" ",
                visible=FALSE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug",
                visible=FALSE))}))

BrawANBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawANBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BrawStats",
                name = "BrawAN",
                version = c(1,0,0),
                options = options,
                results = BrawANResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Analyse Data
#'
#' 
#' @param analysisMode .
#' @param dataLM .
#' @param IV .
#' @param DV .
#' @param inferWhich .
#' @param whichR .
#' @param dataSEM .
#' @param Stage5 .
#' @param Stage4 .
#' @param Stage3 .
#' @param Stage2 .
#' @param Stage1 .
#' @param Stage5On .
#' @param Stage4On .
#' @param Stage3On .
#' @param Stage2On .
#' @param Stage1On .
#' @param causalDirection .
#' @param Depth .
#' @param ShowType .
#' @param clearHistory .
#' @param addDest .
#' @param addSource .
#' @param removeDest .
#' @param removeSource .
#' @param onlySource .
#' @param onlyDest .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$lmGraph} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$lmReport} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$semGraph} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$semReport} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
BrawAN <- function(
    analysisMode,
    dataLM,
    IV,
    DV,
    inferWhich = "r",
    whichR = "Direct",
    dataSEM,
    Stage5,
    Stage4,
    Stage3,
    Stage2,
    Stage1,
    Stage5On = TRUE,
    Stage4On = TRUE,
    Stage3On = TRUE,
    Stage2On = TRUE,
    Stage1On = TRUE,
    causalDirection = "down",
    Depth = "d1",
    ShowType = "ES",
    clearHistory,
    addDest,
    addSource,
    removeDest,
    removeSource,
    onlySource,
    onlyDest) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("BrawAN requires jmvcore to be installed (restart may be required)")

    if ( ! missing(IV)) IV <- jmvcore::resolveQuo(jmvcore::enquo(IV))
    if ( ! missing(DV)) DV <- jmvcore::resolveQuo(jmvcore::enquo(DV))
    if ( ! missing(Stage5)) Stage5 <- jmvcore::resolveQuo(jmvcore::enquo(Stage5))
    if ( ! missing(Stage4)) Stage4 <- jmvcore::resolveQuo(jmvcore::enquo(Stage4))
    if ( ! missing(Stage3)) Stage3 <- jmvcore::resolveQuo(jmvcore::enquo(Stage3))
    if ( ! missing(Stage2)) Stage2 <- jmvcore::resolveQuo(jmvcore::enquo(Stage2))
    if ( ! missing(Stage1)) Stage1 <- jmvcore::resolveQuo(jmvcore::enquo(Stage1))
    if ( ! missing(addDest)) addDest <- jmvcore::resolveQuo(jmvcore::enquo(addDest))
    if ( ! missing(addSource)) addSource <- jmvcore::resolveQuo(jmvcore::enquo(addSource))
    if ( ! missing(removeDest)) removeDest <- jmvcore::resolveQuo(jmvcore::enquo(removeDest))
    if ( ! missing(removeSource)) removeSource <- jmvcore::resolveQuo(jmvcore::enquo(removeSource))
    if ( ! missing(onlySource)) onlySource <- jmvcore::resolveQuo(jmvcore::enquo(onlySource))
    if ( ! missing(onlyDest)) onlyDest <- jmvcore::resolveQuo(jmvcore::enquo(onlyDest))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(IV), IV, NULL),
            `if`( ! missing(DV), DV, NULL),
            `if`( ! missing(Stage5), Stage5, NULL),
            `if`( ! missing(Stage4), Stage4, NULL),
            `if`( ! missing(Stage3), Stage3, NULL),
            `if`( ! missing(Stage2), Stage2, NULL),
            `if`( ! missing(Stage1), Stage1, NULL),
            `if`( ! missing(addDest), addDest, NULL),
            `if`( ! missing(addSource), addSource, NULL),
            `if`( ! missing(removeDest), removeDest, NULL),
            `if`( ! missing(removeSource), removeSource, NULL),
            `if`( ! missing(onlySource), onlySource, NULL),
            `if`( ! missing(onlyDest), onlyDest, NULL))


    options <- BrawANOptions$new(
        analysisMode = analysisMode,
        IV = IV,
        DV = DV,
        inferWhich = inferWhich,
        whichR = whichR,
        Stage5 = Stage5,
        Stage4 = Stage4,
        Stage3 = Stage3,
        Stage2 = Stage2,
        Stage1 = Stage1,
        Stage5On = Stage5On,
        Stage4On = Stage4On,
        Stage3On = Stage3On,
        Stage2On = Stage2On,
        Stage1On = Stage1On,
        causalDirection = causalDirection,
        Depth = Depth,
        ShowType = ShowType,
        clearHistory = clearHistory,
        addDest = addDest,
        addSource = addSource,
        removeDest = removeDest,
        removeSource = removeSource,
        onlySource = onlySource,
        onlyDest = onlyDest)

    analysis <- BrawANClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

